
// This file has been generated by the GUI designer. Do not modify.
namespace WhiteRose
{
	public partial class VntFechaCalendario
	{
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.Calendar Calendario;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button BtnCancelar;
		
		private global::Gtk.Fixed fixed3;
		
		private global::Gtk.Button BtnAceptar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WhiteRose.VntFechaCalendario
			this.Name = "WhiteRose.VntFechaCalendario";
			this.Title = global::Mono.Unix.Catalog.GetString ("VntFechaCalendario");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
			this.WindowPosition = ((global::Gtk.WindowPosition)(2));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child WhiteRose.VntFechaCalendario.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			this.vbox7.BorderWidth = ((uint)(6));
			// Container child vbox7.Gtk.Box+BoxChild
			this.Calendario = new global::Gtk.Calendar ();
			this.Calendario.CanFocus = true;
			this.Calendario.Name = "Calendario";
			this.Calendario.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox7.Add (this.Calendario);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.Calendario]));
			w1.Position = 0;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BtnCancelar = new global::Gtk.Button ();
			this.BtnCancelar.CanFocus = true;
			this.BtnCancelar.Name = "BtnCancelar";
			this.BtnCancelar.UseUnderline = true;
			this.BtnCancelar.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox1.Add (this.BtnCancelar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.BtnCancelar]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.hbox1.Add (this.fixed3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixed3]));
			w3.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BtnAceptar = new global::Gtk.Button ();
			this.BtnAceptar.CanFocus = true;
			this.BtnAceptar.Name = "BtnAceptar";
			this.BtnAceptar.UseUnderline = true;
			this.BtnAceptar.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
			this.hbox1.Add (this.BtnAceptar);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.BtnAceptar]));
			w4.Position = 2;
			this.vbox7.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 281;
			this.DefaultHeight = 248;
			this.Show ();
			this.Calendario.DaySelectedDoubleClick += new global::System.EventHandler (this.OnCalendarioDaySelectedDoubleClick);
			this.BtnCancelar.Clicked += new global::System.EventHandler (this.OnBtnCancelarClicked);
			this.BtnAceptar.Clicked += new global::System.EventHandler (this.OnBtnAceptarClicked);
		}
	}
}
