
// This file has been generated by the GUI designer. Do not modify.
namespace WhiteRose
{
	public partial class VntProcesarVentas
	{
		private global::Gtk.VBox vbox9;
		
		private global::Gtk.Frame frame10;
		
		private global::Gtk.Alignment GtkAlignment6;
		
		private global::Gtk.Label LblNombreEmpresa;
		
		private global::Gtk.VBox vbox10;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.VBox vbox20;
		
		private global::Gtk.HBox hbox25;
		
		private global::Gtk.Label LblNroFact;
		
		private global::Gtk.Entry EntNroFact;
		
		private global::Gtk.Label LblFecha;
		
		private global::Gtk.Entry EntFecha;
		
		private global::Gtk.Label LblHora;
		
		private global::Gtk.Entry EntHora;
		
		private global::Gtk.Frame frame8;
		
		private global::Gtk.Alignment GtkAlignment3;
		
		private global::Gtk.VBox vbox14;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.Label LblRif;
		
		private global::Gtk.Label LblDireccionCliente;
		
		private global::Gtk.VBox vbox8;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Entry EntRifCliente;
		
		private global::Gtk.Button BtnBuscarCliente;
		
		private global::Gtk.Entry EntDireccionCliente;
		
		private global::Gtk.VBox vbox18;
		
		private global::Gtk.Label LblNombreCliente;
		
		private global::Gtk.Label LblTelefono;
		
		private global::Gtk.VBox vbox19;
		
		private global::Gtk.Entry EntNombreCliente;
		
		private global::Gtk.Entry EntTlfCliente;
		
		private global::Gtk.Label LblIdCliente;
		
		private global::Gtk.Frame frame9;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.HBox hbox26;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Label LblCodigoServ;
		
		private global::Gtk.Label LblCantidad;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Entry EntCodServ;
		
		private global::Gtk.Button BtnBuscarServicio;
		
		private global::Gtk.Entry EntCantServ;
		
		private global::Gtk.Fixed fixed4;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Button BtnActualizarServ;
		
		private global::Gtk.Button BtnEliminarServ;
		
		private global::Gtk.Button BtnCancelarActualizacion;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment5;
		
		private global::Gtk.VBox vbox15;
		
		private global::Gtk.RadioButton RbDetal;
		
		private global::Gtk.RadioButton RbMayor;
		
		private global::Gtk.Label LblTipoVenta;
		
		private global::Gtk.Button BtnAnadirServ;
		
		private global::Gtk.Label LblServicios;
		
		private global::Gtk.Frame frame6;
		
		private global::Gtk.Alignment GtkAlignment7;
		
		private global::Gtk.VBox vbox13;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.Label LblSubtotal;
		
		private global::Gtk.Label LblPorcDesc;
		
		private global::Gtk.Label LblBaseImponible;
		
		private global::Gtk.Fixed fixed9;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.Entry EntSubtotal;
		
		private global::Gtk.Entry EntPorcDesc;
		
		private global::Gtk.Entry EntBaseImp;
		
		private global::Gtk.Fixed fixed10;
		
		private global::Gtk.Fixed fixed11;
		
		private global::Gtk.VBox vbox16;
		
		private global::Gtk.Fixed fixed5;
		
		private global::Gtk.Label LblMonto;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label LblIva;
		
		private global::Gtk.Entry EntIva1;
		
		private global::Gtk.Label LblIva2;
		
		private global::Gtk.Label LblMontosPagar1;
		
		private global::Gtk.VBox vbox17;
		
		private global::Gtk.Fixed fixed6;
		
		private global::Gtk.Entry EntMontoDesc;
		
		private global::Gtk.Entry EntIva;
		
		private global::Gtk.Entry EntTotalPagar;
		
		private global::Gtk.Label LblMontosPagar;
		
		private global::Gtk.VBox vbox21;
		
		private global::Gtk.Frame frame7;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView TvServiciosPagar;
		
		private global::Gtk.Label LblServiciosAPagar;
		
		private global::Gtk.VBox vbox22;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Button BtnLimpiar;
		
		private global::Gtk.Button BtnGuardar;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.HBox hbox14;
		
		private global::Gtk.Button BtnCancelar;
		
		private global::Gtk.Button BtnSalir;
		
		private global::Gtk.VBox vbox11;
		
		private global::Gtk.VBox vbox12;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.HBox hbox11;
		
		private global::Gtk.Fixed fixed36;
		
		private global::Gtk.Fixed fixed34;
		
		private global::Gtk.HSeparator hseparator4;
		
		private global::Gtk.Frame frame5;
		
		private global::Gtk.Alignment GtkAlignment8;
		
		private global::Gtk.Label LblFechaHora;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WhiteRose.VntProcesarVentas
			this.Name = "WhiteRose.VntProcesarVentas";
			this.Title = global::Mono.Unix.Catalog.GetString ("Procesar Ventas");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(6));
			// Container child WhiteRose.VntProcesarVentas.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.frame10 = new global::Gtk.Frame ();
			this.frame10.Name = "frame10";
			this.frame10.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame10.Gtk.Container+ContainerChild
			this.GtkAlignment6 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment6.Name = "GtkAlignment6";
			this.GtkAlignment6.LeftPadding = ((uint)(12));
			// Container child GtkAlignment6.Gtk.Container+ContainerChild
			this.LblNombreEmpresa = new global::Gtk.Label ();
			this.LblNombreEmpresa.Name = "LblNombreEmpresa";
			this.LblNombreEmpresa.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Mr. Robot Tech</b> - Procesar Ventas");
			this.LblNombreEmpresa.UseMarkup = true;
			this.LblNombreEmpresa.Justify = ((global::Gtk.Justification)(2));
			this.GtkAlignment6.Add (this.LblNombreEmpresa);
			this.frame10.Add (this.GtkAlignment6);
			this.vbox9.Add (this.frame10);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.frame10]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox20 = new global::Gtk.VBox ();
			this.vbox20.Name = "vbox20";
			this.vbox20.Spacing = 6;
			// Container child vbox20.Gtk.Box+BoxChild
			this.hbox25 = new global::Gtk.HBox ();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 6;
			this.hbox25.BorderWidth = ((uint)(6));
			// Container child hbox25.Gtk.Box+BoxChild
			this.LblNroFact = new global::Gtk.Label ();
			this.LblNroFact.Name = "LblNroFact";
			this.LblNroFact.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Número de Factura:</b>");
			this.LblNroFact.UseMarkup = true;
			this.hbox25.Add (this.LblNroFact);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.LblNroFact]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.EntNroFact = new global::Gtk.Entry ();
			this.EntNroFact.CanFocus = true;
			this.EntNroFact.Name = "EntNroFact";
			this.EntNroFact.IsEditable = false;
			this.EntNroFact.InvisibleChar = '•';
			this.hbox25.Add (this.EntNroFact);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.EntNroFact]));
			w5.Position = 1;
			// Container child hbox25.Gtk.Box+BoxChild
			this.LblFecha = new global::Gtk.Label ();
			this.LblFecha.Name = "LblFecha";
			this.LblFecha.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha:");
			this.hbox25.Add (this.LblFecha);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.LblFecha]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.EntFecha = new global::Gtk.Entry ();
			this.EntFecha.CanFocus = true;
			this.EntFecha.Name = "EntFecha";
			this.EntFecha.IsEditable = true;
			this.EntFecha.InvisibleChar = '●';
			this.hbox25.Add (this.EntFecha);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.EntFecha]));
			w7.Position = 3;
			// Container child hbox25.Gtk.Box+BoxChild
			this.LblHora = new global::Gtk.Label ();
			this.LblHora.Name = "LblHora";
			this.LblHora.LabelProp = global::Mono.Unix.Catalog.GetString ("Hora:");
			this.hbox25.Add (this.LblHora);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.LblHora]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.EntHora = new global::Gtk.Entry ();
			this.EntHora.CanFocus = true;
			this.EntHora.Name = "EntHora";
			this.EntHora.IsEditable = true;
			this.EntHora.InvisibleChar = '●';
			this.hbox25.Add (this.EntHora);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.EntHora]));
			w9.Position = 5;
			this.vbox20.Add (this.hbox25);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox20 [this.hbox25]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox20.Gtk.Box+BoxChild
			this.frame8 = new global::Gtk.Frame ();
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame8.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			this.GtkAlignment3.BorderWidth = ((uint)(6));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Homogeneous = true;
			this.vbox7.Spacing = 9;
			// Container child vbox7.Gtk.Box+BoxChild
			this.LblRif = new global::Gtk.Label ();
			this.LblRif.Name = "LblRif";
			this.LblRif.Xalign = 1F;
			this.LblRif.LabelProp = global::Mono.Unix.Catalog.GetString ("Rif:");
			this.vbox7.Add (this.LblRif);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.LblRif]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.LblDireccionCliente = new global::Gtk.Label ();
			this.LblDireccionCliente.Name = "LblDireccionCliente";
			this.LblDireccionCliente.Xalign = 1F;
			this.LblDireccionCliente.LabelProp = global::Mono.Unix.Catalog.GetString ("Dirección:");
			this.vbox7.Add (this.LblDireccionCliente);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.LblDireccionCliente]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox4.Add (this.vbox7);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox7]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Homogeneous = true;
			this.vbox8.Spacing = 9;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.EntRifCliente = new global::Gtk.Entry ();
			this.EntRifCliente.CanFocus = true;
			this.EntRifCliente.Name = "EntRifCliente";
			this.EntRifCliente.IsEditable = true;
			this.EntRifCliente.MaxLength = 15;
			this.EntRifCliente.InvisibleChar = '•';
			this.hbox6.Add (this.EntRifCliente);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.EntRifCliente]));
			w14.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.BtnBuscarCliente = new global::Gtk.Button ();
			this.BtnBuscarCliente.CanFocus = true;
			this.BtnBuscarCliente.Name = "BtnBuscarCliente";
			this.BtnBuscarCliente.UseUnderline = true;
			global::Gtk.Image w15 = new global::Gtk.Image ();
			w15.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Menu);
			this.BtnBuscarCliente.Image = w15;
			this.hbox6.Add (this.BtnBuscarCliente);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.BtnBuscarCliente]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox8.Add (this.hbox6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox6]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.EntDireccionCliente = new global::Gtk.Entry ();
			this.EntDireccionCliente.CanFocus = true;
			this.EntDireccionCliente.Name = "EntDireccionCliente";
			this.EntDireccionCliente.IsEditable = false;
			this.EntDireccionCliente.InvisibleChar = '•';
			this.vbox8.Add (this.EntDireccionCliente);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.EntDireccionCliente]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox4.Add (this.vbox8);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox8]));
			w19.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox18 = new global::Gtk.VBox ();
			this.vbox18.Name = "vbox18";
			this.vbox18.Homogeneous = true;
			this.vbox18.Spacing = 9;
			// Container child vbox18.Gtk.Box+BoxChild
			this.LblNombreCliente = new global::Gtk.Label ();
			this.LblNombreCliente.Name = "LblNombreCliente";
			this.LblNombreCliente.Xalign = 1F;
			this.LblNombreCliente.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre:");
			this.vbox18.Add (this.LblNombreCliente);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox18 [this.LblNombreCliente]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox18.Gtk.Box+BoxChild
			this.LblTelefono = new global::Gtk.Label ();
			this.LblTelefono.Name = "LblTelefono";
			this.LblTelefono.Xalign = 1F;
			this.LblTelefono.LabelProp = global::Mono.Unix.Catalog.GetString ("Teléfono:");
			this.vbox18.Add (this.LblTelefono);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox18 [this.LblTelefono]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.hbox4.Add (this.vbox18);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox18]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox19 = new global::Gtk.VBox ();
			this.vbox19.Name = "vbox19";
			this.vbox19.Homogeneous = true;
			this.vbox19.Spacing = 9;
			// Container child vbox19.Gtk.Box+BoxChild
			this.EntNombreCliente = new global::Gtk.Entry ();
			this.EntNombreCliente.CanFocus = true;
			this.EntNombreCliente.Name = "EntNombreCliente";
			this.EntNombreCliente.IsEditable = false;
			this.EntNombreCliente.InvisibleChar = '•';
			this.vbox19.Add (this.EntNombreCliente);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox19 [this.EntNombreCliente]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox19.Gtk.Box+BoxChild
			this.EntTlfCliente = new global::Gtk.Entry ();
			this.EntTlfCliente.CanFocus = true;
			this.EntTlfCliente.Name = "EntTlfCliente";
			this.EntTlfCliente.IsEditable = false;
			this.EntTlfCliente.InvisibleChar = '•';
			this.vbox19.Add (this.EntTlfCliente);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox19 [this.EntTlfCliente]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.hbox4.Add (this.vbox19);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox19]));
			w25.Position = 3;
			this.vbox14.Add (this.hbox4);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox4]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			this.GtkAlignment3.Add (this.vbox14);
			this.frame8.Add (this.GtkAlignment3);
			this.LblIdCliente = new global::Gtk.Label ();
			this.LblIdCliente.Name = "LblIdCliente";
			this.LblIdCliente.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Identificación del Cliente</b>");
			this.LblIdCliente.UseMarkup = true;
			this.frame8.LabelWidget = this.LblIdCliente;
			this.vbox20.Add (this.frame8);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox20 [this.frame8]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox20.Gtk.Box+BoxChild
			this.frame9 = new global::Gtk.Frame ();
			this.frame9.Name = "frame9";
			this.frame9.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame9.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			this.GtkAlignment4.BorderWidth = ((uint)(6));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.hbox26 = new global::Gtk.HBox ();
			this.hbox26.Name = "hbox26";
			this.hbox26.Spacing = 6;
			// Container child hbox26.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Homogeneous = true;
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.LblCodigoServ = new global::Gtk.Label ();
			this.LblCodigoServ.Name = "LblCodigoServ";
			this.LblCodigoServ.Xalign = 1F;
			this.LblCodigoServ.LabelProp = global::Mono.Unix.Catalog.GetString ("Código:");
			this.vbox4.Add (this.LblCodigoServ);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.LblCodigoServ]));
			w30.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.LblCantidad = new global::Gtk.Label ();
			this.LblCantidad.Name = "LblCantidad";
			this.LblCantidad.Xalign = 1F;
			this.LblCantidad.LabelProp = global::Mono.Unix.Catalog.GetString ("Cantidad:");
			this.vbox4.Add (this.LblCantidad);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.LblCantidad]));
			w31.Position = 1;
			this.hbox26.Add (this.vbox4);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.vbox4]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Homogeneous = true;
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.EntCodServ = new global::Gtk.Entry ();
			this.EntCodServ.CanFocus = true;
			this.EntCodServ.Name = "EntCodServ";
			this.EntCodServ.IsEditable = true;
			this.EntCodServ.MaxLength = 3;
			this.EntCodServ.InvisibleChar = '•';
			this.hbox5.Add (this.EntCodServ);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.EntCodServ]));
			w33.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.BtnBuscarServicio = new global::Gtk.Button ();
			this.BtnBuscarServicio.CanFocus = true;
			this.BtnBuscarServicio.Name = "BtnBuscarServicio";
			this.BtnBuscarServicio.UseUnderline = true;
			global::Gtk.Image w34 = new global::Gtk.Image ();
			w34.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Button);
			this.BtnBuscarServicio.Image = w34;
			this.hbox5.Add (this.BtnBuscarServicio);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.BtnBuscarServicio]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox2.Add (this.hbox5);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.EntCantServ = new global::Gtk.Entry ();
			this.EntCantServ.CanFocus = true;
			this.EntCantServ.Name = "EntCantServ";
			this.EntCantServ.IsEditable = true;
			this.EntCantServ.MaxLength = 5;
			this.EntCantServ.InvisibleChar = '•';
			this.vbox2.Add (this.EntCantServ);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.EntCantServ]));
			w37.Position = 1;
			this.hbox26.Add (this.vbox2);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.vbox2]));
			w38.Position = 1;
			// Container child hbox26.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.WidthRequest = 15;
			this.fixed4.HeightRequest = 3;
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.hbox26.Add (this.fixed4);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.fixed4]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(6));
			// Container child vbox3.Gtk.Box+BoxChild
			this.BtnActualizarServ = new global::Gtk.Button ();
			this.BtnActualizarServ.Sensitive = false;
			this.BtnActualizarServ.CanFocus = true;
			this.BtnActualizarServ.Name = "BtnActualizarServ";
			this.BtnActualizarServ.UseUnderline = true;
			this.BtnActualizarServ.Label = global::Mono.Unix.Catalog.GetString ("_Actualizar");
			this.vbox3.Add (this.BtnActualizarServ);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.BtnActualizarServ]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.BtnEliminarServ = new global::Gtk.Button ();
			this.BtnEliminarServ.Sensitive = false;
			this.BtnEliminarServ.CanFocus = true;
			this.BtnEliminarServ.Name = "BtnEliminarServ";
			this.BtnEliminarServ.UseUnderline = true;
			this.BtnEliminarServ.Label = global::Mono.Unix.Catalog.GetString ("Eliminar");
			this.vbox3.Add (this.BtnEliminarServ);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.BtnEliminarServ]));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.BtnCancelarActualizacion = new global::Gtk.Button ();
			this.BtnCancelarActualizacion.Sensitive = false;
			this.BtnCancelarActualizacion.CanFocus = true;
			this.BtnCancelarActualizacion.Name = "BtnCancelarActualizacion";
			this.BtnCancelarActualizacion.UseUnderline = true;
			this.BtnCancelarActualizacion.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.vbox3.Add (this.BtnCancelarActualizacion);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.BtnCancelarActualizacion]));
			w42.Position = 2;
			w42.Expand = false;
			w42.Fill = false;
			this.hbox26.Add (this.vbox3);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.vbox3]));
			w43.Position = 3;
			// Container child hbox26.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment5.Name = "GtkAlignment5";
			this.GtkAlignment5.LeftPadding = ((uint)(12));
			// Container child GtkAlignment5.Gtk.Container+ContainerChild
			this.vbox15 = new global::Gtk.VBox ();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.RbDetal = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Detal"));
			this.RbDetal.CanFocus = true;
			this.RbDetal.Name = "RbDetal";
			this.RbDetal.DrawIndicator = true;
			this.RbDetal.UseUnderline = true;
			this.RbDetal.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox15.Add (this.RbDetal);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.RbDetal]));
			w44.Position = 0;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.RbMayor = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Mayor"));
			this.RbMayor.CanFocus = true;
			this.RbMayor.Name = "RbMayor";
			this.RbMayor.DrawIndicator = true;
			this.RbMayor.UseUnderline = true;
			this.RbMayor.Group = this.RbDetal.Group;
			this.vbox15.Add (this.RbMayor);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.RbMayor]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			this.GtkAlignment5.Add (this.vbox15);
			this.frame1.Add (this.GtkAlignment5);
			this.LblTipoVenta = new global::Gtk.Label ();
			this.LblTipoVenta.Name = "LblTipoVenta";
			this.LblTipoVenta.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Tipo de Venta</b>");
			this.LblTipoVenta.UseMarkup = true;
			this.frame1.LabelWidget = this.LblTipoVenta;
			this.vbox1.Add (this.frame1);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
			w48.Position = 0;
			w48.Expand = false;
			w48.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.BtnAnadirServ = new global::Gtk.Button ();
			this.BtnAnadirServ.HeightRequest = 40;
			this.BtnAnadirServ.CanFocus = true;
			this.BtnAnadirServ.Name = "BtnAnadirServ";
			this.BtnAnadirServ.UseUnderline = true;
			this.BtnAnadirServ.Label = global::Mono.Unix.Catalog.GetString ("Añadir");
			this.vbox1.Add (this.BtnAnadirServ);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.BtnAnadirServ]));
			w49.Position = 1;
			w49.Expand = false;
			w49.Fill = false;
			this.hbox26.Add (this.vbox1);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.vbox1]));
			w50.Position = 4;
			this.GtkAlignment4.Add (this.hbox26);
			this.frame9.Add (this.GtkAlignment4);
			this.LblServicios = new global::Gtk.Label ();
			this.LblServicios.Name = "LblServicios";
			this.LblServicios.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Ingresar Servicios</b>");
			this.LblServicios.UseMarkup = true;
			this.frame9.LabelWidget = this.LblServicios;
			this.vbox20.Add (this.frame9);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox20 [this.frame9]));
			w53.Position = 2;
			w53.Expand = false;
			w53.Fill = false;
			// Container child vbox20.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment7 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment7.Name = "GtkAlignment7";
			this.GtkAlignment7.LeftPadding = ((uint)(12));
			this.GtkAlignment7.BorderWidth = ((uint)(6));
			// Container child GtkAlignment7.Gtk.Container+ContainerChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Homogeneous = true;
			this.vbox5.Spacing = 9;
			// Container child vbox5.Gtk.Box+BoxChild
			this.LblSubtotal = new global::Gtk.Label ();
			this.LblSubtotal.Name = "LblSubtotal";
			this.LblSubtotal.Xalign = 1F;
			this.LblSubtotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Subtotal:");
			this.vbox5.Add (this.LblSubtotal);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.LblSubtotal]));
			w54.Position = 0;
			w54.Expand = false;
			w54.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.LblPorcDesc = new global::Gtk.Label ();
			this.LblPorcDesc.Name = "LblPorcDesc";
			this.LblPorcDesc.Xalign = 1F;
			this.LblPorcDesc.LabelProp = global::Mono.Unix.Catalog.GetString ("% Descuento:");
			this.vbox5.Add (this.LblPorcDesc);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.LblPorcDesc]));
			w55.Position = 1;
			w55.Expand = false;
			w55.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.LblBaseImponible = new global::Gtk.Label ();
			this.LblBaseImponible.Name = "LblBaseImponible";
			this.LblBaseImponible.Xalign = 1F;
			this.LblBaseImponible.LabelProp = global::Mono.Unix.Catalog.GetString ("Base Imponible:");
			this.vbox5.Add (this.LblBaseImponible);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.LblBaseImponible]));
			w56.Position = 2;
			w56.Expand = false;
			w56.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.fixed9 = new global::Gtk.Fixed ();
			this.fixed9.Name = "fixed9";
			this.fixed9.HasWindow = false;
			this.vbox5.Add (this.fixed9);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.fixed9]));
			w57.PackType = ((global::Gtk.PackType)(1));
			w57.Position = 3;
			this.hbox2.Add (this.vbox5);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox5]));
			w58.Position = 0;
			w58.Expand = false;
			w58.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Homogeneous = true;
			this.vbox6.Spacing = 9;
			// Container child vbox6.Gtk.Box+BoxChild
			this.EntSubtotal = new global::Gtk.Entry ();
			this.EntSubtotal.CanFocus = true;
			this.EntSubtotal.Name = "EntSubtotal";
			this.EntSubtotal.IsEditable = false;
			this.EntSubtotal.InvisibleChar = '•';
			this.vbox6.Add (this.EntSubtotal);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.EntSubtotal]));
			w59.Position = 0;
			w59.Expand = false;
			w59.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.EntPorcDesc = new global::Gtk.Entry ();
			this.EntPorcDesc.CanFocus = true;
			this.EntPorcDesc.Name = "EntPorcDesc";
			this.EntPorcDesc.Text = global::Mono.Unix.Catalog.GetString ("0");
			this.EntPorcDesc.IsEditable = true;
			this.EntPorcDesc.MaxLength = 2;
			this.EntPorcDesc.InvisibleChar = '•';
			this.vbox6.Add (this.EntPorcDesc);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.EntPorcDesc]));
			w60.Position = 1;
			w60.Expand = false;
			w60.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.EntBaseImp = new global::Gtk.Entry ();
			this.EntBaseImp.CanFocus = true;
			this.EntBaseImp.Name = "EntBaseImp";
			this.EntBaseImp.IsEditable = false;
			this.EntBaseImp.InvisibleChar = '•';
			this.vbox6.Add (this.EntBaseImp);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.EntBaseImp]));
			w61.Position = 2;
			w61.Expand = false;
			w61.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.fixed10 = new global::Gtk.Fixed ();
			this.fixed10.Name = "fixed10";
			this.fixed10.HasWindow = false;
			this.vbox6.Add (this.fixed10);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.fixed10]));
			w62.Position = 3;
			this.hbox2.Add (this.vbox6);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox6]));
			w63.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed11 = new global::Gtk.Fixed ();
			this.fixed11.Name = "fixed11";
			this.fixed11.HasWindow = false;
			this.hbox2.Add (this.fixed11);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed11]));
			w64.Position = 2;
			w64.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox16 = new global::Gtk.VBox ();
			this.vbox16.Name = "vbox16";
			this.vbox16.Homogeneous = true;
			this.vbox16.Spacing = 9;
			// Container child vbox16.Gtk.Box+BoxChild
			this.fixed5 = new global::Gtk.Fixed ();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			this.vbox16.Add (this.fixed5);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.fixed5]));
			w65.Position = 0;
			// Container child vbox16.Gtk.Box+BoxChild
			this.LblMonto = new global::Gtk.Label ();
			this.LblMonto.Name = "LblMonto";
			this.LblMonto.Xalign = 1F;
			this.LblMonto.LabelProp = global::Mono.Unix.Catalog.GetString ("Monto del Descuento:");
			this.vbox16.Add (this.LblMonto);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.LblMonto]));
			w66.Position = 1;
			w66.Expand = false;
			w66.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.LblIva = new global::Gtk.Label ();
			this.LblIva.WidthRequest = 83;
			this.LblIva.Name = "LblIva";
			this.LblIva.Xalign = 1F;
			this.LblIva.LabelProp = global::Mono.Unix.Catalog.GetString ("IVA (");
			this.hbox3.Add (this.LblIva);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.LblIva]));
			w67.Position = 0;
			w67.Expand = false;
			w67.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.EntIva1 = new global::Gtk.Entry ();
			this.EntIva1.WidthRequest = 30;
			this.EntIva1.CanFocus = true;
			this.EntIva1.Name = "EntIva1";
			this.EntIva1.Text = global::Mono.Unix.Catalog.GetString ("12");
			this.EntIva1.IsEditable = true;
			this.EntIva1.MaxLength = 2;
			this.EntIva1.InvisibleChar = '•';
			this.hbox3.Add (this.EntIva1);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.EntIva1]));
			w68.Position = 1;
			w68.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.LblIva2 = new global::Gtk.Label ();
			this.LblIva2.Name = "LblIva2";
			this.LblIva2.Xalign = 1F;
			this.LblIva2.LabelProp = global::Mono.Unix.Catalog.GetString ("%):");
			this.hbox3.Add (this.LblIva2);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.LblIva2]));
			w69.Position = 2;
			w69.Expand = false;
			w69.Fill = false;
			this.vbox16.Add (this.hbox3);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.hbox3]));
			w70.Position = 2;
			// Container child vbox16.Gtk.Box+BoxChild
			this.LblMontosPagar1 = new global::Gtk.Label ();
			this.LblMontosPagar1.Name = "LblMontosPagar1";
			this.LblMontosPagar1.Xalign = 1F;
			this.LblMontosPagar1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Total a Pagar:</b>");
			this.LblMontosPagar1.UseMarkup = true;
			this.vbox16.Add (this.LblMontosPagar1);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.LblMontosPagar1]));
			w71.Position = 3;
			w71.Expand = false;
			w71.Fill = false;
			this.hbox2.Add (this.vbox16);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox16]));
			w72.Position = 3;
			w72.Expand = false;
			w72.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox ();
			this.vbox17.Name = "vbox17";
			this.vbox17.Homogeneous = true;
			this.vbox17.Spacing = 9;
			// Container child vbox17.Gtk.Box+BoxChild
			this.fixed6 = new global::Gtk.Fixed ();
			this.fixed6.Name = "fixed6";
			this.fixed6.HasWindow = false;
			this.vbox17.Add (this.fixed6);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.fixed6]));
			w73.Position = 0;
			// Container child vbox17.Gtk.Box+BoxChild
			this.EntMontoDesc = new global::Gtk.Entry ();
			this.EntMontoDesc.CanFocus = true;
			this.EntMontoDesc.Name = "EntMontoDesc";
			this.EntMontoDesc.IsEditable = false;
			this.EntMontoDesc.InvisibleChar = '•';
			this.vbox17.Add (this.EntMontoDesc);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.EntMontoDesc]));
			w74.Position = 1;
			w74.Expand = false;
			w74.Fill = false;
			// Container child vbox17.Gtk.Box+BoxChild
			this.EntIva = new global::Gtk.Entry ();
			this.EntIva.CanFocus = true;
			this.EntIva.Name = "EntIva";
			this.EntIva.IsEditable = false;
			this.EntIva.InvisibleChar = '•';
			this.vbox17.Add (this.EntIva);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.EntIva]));
			w75.Position = 2;
			w75.Expand = false;
			w75.Fill = false;
			// Container child vbox17.Gtk.Box+BoxChild
			this.EntTotalPagar = new global::Gtk.Entry ();
			this.EntTotalPagar.CanFocus = true;
			this.EntTotalPagar.Name = "EntTotalPagar";
			this.EntTotalPagar.IsEditable = false;
			this.EntTotalPagar.InvisibleChar = '•';
			this.vbox17.Add (this.EntTotalPagar);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.EntTotalPagar]));
			w76.Position = 3;
			w76.Expand = false;
			w76.Fill = false;
			this.hbox2.Add (this.vbox17);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox17]));
			w77.Position = 4;
			this.vbox13.Add (this.hbox2);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox2]));
			w78.Position = 0;
			w78.Expand = false;
			w78.Fill = false;
			this.GtkAlignment7.Add (this.vbox13);
			this.frame6.Add (this.GtkAlignment7);
			this.LblMontosPagar = new global::Gtk.Label ();
			this.LblMontosPagar.Name = "LblMontosPagar";
			this.LblMontosPagar.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Descripción del Monto a Pagar</b>");
			this.LblMontosPagar.UseMarkup = true;
			this.frame6.LabelWidget = this.LblMontosPagar;
			this.vbox20.Add (this.frame6);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vbox20 [this.frame6]));
			w81.Position = 3;
			w81.Expand = false;
			w81.Fill = false;
			this.hbox1.Add (this.vbox20);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox20]));
			w82.Position = 0;
			w82.Expand = false;
			w82.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox21 = new global::Gtk.VBox ();
			this.vbox21.Name = "vbox21";
			this.vbox21.Spacing = 6;
			// Container child vbox21.Gtk.Box+BoxChild
			this.frame7 = new global::Gtk.Frame ();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			this.GtkAlignment2.BorderWidth = ((uint)(6));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TvServiciosPagar = new global::Gtk.TreeView ();
			this.TvServiciosPagar.CanFocus = true;
			this.TvServiciosPagar.Name = "TvServiciosPagar";
			this.GtkScrolledWindow.Add (this.TvServiciosPagar);
			this.GtkAlignment2.Add (this.GtkScrolledWindow);
			this.frame7.Add (this.GtkAlignment2);
			this.LblServiciosAPagar = new global::Gtk.Label ();
			this.LblServiciosAPagar.Name = "LblServiciosAPagar";
			this.LblServiciosAPagar.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Servicios a Pagar</b>");
			this.LblServiciosAPagar.UseMarkup = true;
			this.frame7.LabelWidget = this.LblServiciosAPagar;
			this.vbox21.Add (this.frame7);
			global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.vbox21 [this.frame7]));
			w86.Position = 0;
			// Container child vbox21.Gtk.Box+BoxChild
			this.vbox22 = new global::Gtk.VBox ();
			this.vbox22.Name = "vbox22";
			this.vbox22.Spacing = 6;
			// Container child vbox22.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox7.Add (this.fixed1);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.fixed1]));
			w87.Position = 0;
			this.vbox22.Add (this.hbox7);
			global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.vbox22 [this.hbox7]));
			w88.Position = 0;
			w88.Expand = false;
			w88.Fill = false;
			// Container child vbox22.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Homogeneous = true;
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.BtnLimpiar = new global::Gtk.Button ();
			this.BtnLimpiar.CanFocus = true;
			this.BtnLimpiar.Name = "BtnLimpiar";
			this.BtnLimpiar.UseUnderline = true;
			this.BtnLimpiar.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
			this.hbox8.Add (this.BtnLimpiar);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.BtnLimpiar]));
			w89.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.BtnGuardar = new global::Gtk.Button ();
			this.BtnGuardar.Sensitive = false;
			this.BtnGuardar.CanFocus = true;
			this.BtnGuardar.Name = "BtnGuardar";
			this.BtnGuardar.UseUnderline = true;
			this.BtnGuardar.Label = global::Mono.Unix.Catalog.GetString ("Guardar");
			this.hbox8.Add (this.BtnGuardar);
			global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.BtnGuardar]));
			w90.Position = 1;
			this.vbox22.Add (this.hbox8);
			global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.vbox22 [this.hbox8]));
			w91.Position = 1;
			w91.Expand = false;
			w91.Fill = false;
			// Container child vbox22.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox9.Add (this.fixed2);
			global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.fixed2]));
			w92.Position = 0;
			this.vbox22.Add (this.hbox9);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.vbox22 [this.hbox9]));
			w93.Position = 2;
			w93.Expand = false;
			w93.Fill = false;
			// Container child vbox22.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Homogeneous = true;
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.BtnCancelar = new global::Gtk.Button ();
			this.BtnCancelar.CanFocus = true;
			this.BtnCancelar.Name = "BtnCancelar";
			this.BtnCancelar.UseUnderline = true;
			this.BtnCancelar.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox14.Add (this.BtnCancelar);
			global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.BtnCancelar]));
			w94.Position = 0;
			// Container child hbox14.Gtk.Box+BoxChild
			this.BtnSalir = new global::Gtk.Button ();
			this.BtnSalir.CanFocus = true;
			this.BtnSalir.Name = "BtnSalir";
			this.BtnSalir.UseUnderline = true;
			this.BtnSalir.Label = global::Mono.Unix.Catalog.GetString ("Salir");
			this.hbox14.Add (this.BtnSalir);
			global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.BtnSalir]));
			w95.Position = 1;
			this.vbox22.Add (this.hbox14);
			global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.vbox22 [this.hbox14]));
			w96.Position = 3;
			w96.Expand = false;
			w96.Fill = false;
			this.vbox21.Add (this.vbox22);
			global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.vbox21 [this.vbox22]));
			w97.Position = 1;
			w97.Expand = false;
			w97.Fill = false;
			this.hbox1.Add (this.vbox21);
			global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox21]));
			w98.Position = 1;
			this.vbox10.Add (this.hbox1);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox1]));
			w99.Position = 0;
			w99.Expand = false;
			w99.Fill = false;
			this.vbox9.Add (this.vbox10);
			global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vbox10]));
			w100.Position = 1;
			w100.Expand = false;
			w100.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.fixed36 = new global::Gtk.Fixed ();
			this.fixed36.Name = "fixed36";
			this.fixed36.HasWindow = false;
			this.hbox11.Add (this.fixed36);
			global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.fixed36]));
			w101.Position = 0;
			// Container child hbox11.Gtk.Box+BoxChild
			this.fixed34 = new global::Gtk.Fixed ();
			this.fixed34.Name = "fixed34";
			this.fixed34.HasWindow = false;
			this.hbox11.Add (this.fixed34);
			global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.fixed34]));
			w102.Position = 1;
			this.hbox10.Add (this.hbox11);
			global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.hbox11]));
			w103.Position = 0;
			this.vbox12.Add (this.hbox10);
			global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox10]));
			w104.Position = 0;
			this.vbox11.Add (this.vbox12);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.vbox12]));
			w105.Position = 0;
			w105.Expand = false;
			w105.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator ();
			this.hseparator4.Name = "hseparator4";
			this.vbox11.Add (this.hseparator4);
			global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hseparator4]));
			w106.Position = 1;
			w106.Expand = false;
			w106.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment8 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment8.Name = "GtkAlignment8";
			this.GtkAlignment8.LeftPadding = ((uint)(12));
			// Container child GtkAlignment8.Gtk.Container+ContainerChild
			this.LblFechaHora = new global::Gtk.Label ();
			this.LblFechaHora.Name = "LblFechaHora";
			this.LblFechaHora.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha y Hora");
			this.GtkAlignment8.Add (this.LblFechaHora);
			this.frame5.Add (this.GtkAlignment8);
			this.vbox11.Add (this.frame5);
			global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.frame5]));
			w109.Position = 2;
			w109.Expand = false;
			w109.Fill = false;
			this.vbox9.Add (this.vbox11);
			global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vbox11]));
			w110.Position = 2;
			w110.Expand = false;
			w110.Fill = false;
			this.Add (this.vbox9);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1253;
			this.DefaultHeight = 588;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.EntRifCliente.Changed += new global::System.EventHandler (this.OnEntRifClienteChanged);
			this.BtnBuscarCliente.Clicked += new global::System.EventHandler (this.OnBtnBuscarClienteClicked);
			this.EntCodServ.Changed += new global::System.EventHandler (this.OnEntCodServChanged);
			this.BtnBuscarServicio.Clicked += new global::System.EventHandler (this.OnBtnBuscarServicioClicked);
			this.EntCantServ.Changed += new global::System.EventHandler (this.OnEntCantServChanged);
			this.BtnActualizarServ.Clicked += new global::System.EventHandler (this.OnBtnActualizarServClicked);
			this.BtnEliminarServ.Clicked += new global::System.EventHandler (this.OnBtnEliminarServClicked);
			this.BtnAnadirServ.Clicked += new global::System.EventHandler (this.OnBtnAnadirServClicked);
			this.EntPorcDesc.Changed += new global::System.EventHandler (this.OnEntPorcDescChanged);
			this.EntIva1.Changed += new global::System.EventHandler (this.OnEntIva1Changed);
			this.TvServiciosPagar.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTvServiciosPagarRowActivated);
			this.BtnLimpiar.Clicked += new global::System.EventHandler (this.OnBtnLimpiarClicked);
			this.BtnGuardar.Clicked += new global::System.EventHandler (this.OnBtnGuardarClicked);
			this.BtnCancelar.Clicked += new global::System.EventHandler (this.OnBtnCancelarClicked);
			this.BtnSalir.Clicked += new global::System.EventHandler (this.OnBtnSalirClicked);
		}
	}
}
