
// This file has been generated by the GUI designer. Do not modify.
namespace WhiteRose
{
	public partial class VntActualizarUsuarios
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox14;
		
		private global::Gtk.VBox vbox8;
		
		private global::Gtk.Label LblCodUsuarioAnadio;
		
		private global::Gtk.Label LblCodigo;
		
		private global::Gtk.Label LblCedula;
		
		private global::Gtk.Label LblNombre;
		
		private global::Gtk.Label LblApellido;
		
		private global::Gtk.VBox vbox9;
		
		private global::Gtk.Entry EntCodigoReg;
		
		private global::Gtk.Entry EntCodigo;
		
		private global::Gtk.HBox hbox15;
		
		private global::Gtk.Entry EntCedula;
		
		private global::Gtk.Entry EntNombre;
		
		private global::Gtk.Entry EntApellido;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Label LblFechaIng;
		
		private global::Gtk.Label LblUsuario;
		
		private global::Gtk.Label LblContrasena;
		
		private global::Gtk.Label LblCorreo;
		
		private global::Gtk.Label LblPista;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.Entry EntFechaIng;
		
		private global::Gtk.Entry EntUsuario;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Entry EntContrasena;
		
		private global::Gtk.Button BtnVer;
		
		private global::Gtk.Entry EntEmail;
		
		private global::Gtk.Entry EntPista;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label LblTipoUsuario;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.RadioButton RbAdministrador;
		
		private global::Gtk.RadioButton RbVendedor;
		
		private global::Gtk.RadioButton RbActualizador;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.Button BtnIncluir;
		
		private global::Gtk.Button BtnModificar;
		
		private global::Gtk.Button BtnEliminar;
		
		private global::Gtk.HBox hbox12;
		
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView TvUsuarios;
		
		private global::Gtk.Label LblUsuariosSistema;
		
		private global::Gtk.HBox hbox13;
		
		private global::Gtk.Button BtnLimpiar;
		
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Button BtnCancelar;
		
		private global::Gtk.Button BtnSalir;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.Label LblFechaHora;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WhiteRose.VntActualizarUsuarios
			this.Name = "WhiteRose.VntActualizarUsuarios";
			this.Title = global::Mono.Unix.Catalog.GetString ("Actualizar Usuarios");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(12));
			// Container child WhiteRose.VntActualizarUsuarios.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 17;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 20;
			// Container child hbox14.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Homogeneous = true;
			this.vbox8.Spacing = 9;
			// Container child vbox8.Gtk.Box+BoxChild
			this.LblCodUsuarioAnadio = new global::Gtk.Label ();
			this.LblCodUsuarioAnadio.Name = "LblCodUsuarioAnadio";
			this.LblCodUsuarioAnadio.Xalign = 1F;
			this.LblCodUsuarioAnadio.LabelProp = global::Mono.Unix.Catalog.GetString ("Añadido por:");
			this.vbox8.Add (this.LblCodUsuarioAnadio);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.LblCodUsuarioAnadio]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.LblCodigo = new global::Gtk.Label ();
			this.LblCodigo.Name = "LblCodigo";
			this.LblCodigo.Xalign = 1F;
			this.LblCodigo.LabelProp = global::Mono.Unix.Catalog.GetString ("Código:");
			this.vbox8.Add (this.LblCodigo);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.LblCodigo]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.LblCedula = new global::Gtk.Label ();
			this.LblCedula.Name = "LblCedula";
			this.LblCedula.Xalign = 1F;
			this.LblCedula.LabelProp = global::Mono.Unix.Catalog.GetString ("Cédula:");
			this.vbox8.Add (this.LblCedula);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.LblCedula]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.LblNombre = new global::Gtk.Label ();
			this.LblNombre.Name = "LblNombre";
			this.LblNombre.Xalign = 1F;
			this.LblNombre.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre:");
			this.vbox8.Add (this.LblNombre);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.LblNombre]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.LblApellido = new global::Gtk.Label ();
			this.LblApellido.Name = "LblApellido";
			this.LblApellido.Xalign = 1F;
			this.LblApellido.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellido:");
			this.vbox8.Add (this.LblApellido);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.LblApellido]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox14.Add (this.vbox8);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.vbox8]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Homogeneous = true;
			this.vbox9.Spacing = 9;
			// Container child vbox9.Gtk.Box+BoxChild
			this.EntCodigoReg = new global::Gtk.Entry ();
			this.EntCodigoReg.CanFocus = true;
			this.EntCodigoReg.Name = "EntCodigoReg";
			this.EntCodigoReg.IsEditable = false;
			this.EntCodigoReg.InvisibleChar = '•';
			this.vbox9.Add (this.EntCodigoReg);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.EntCodigoReg]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.EntCodigo = new global::Gtk.Entry ();
			this.EntCodigo.CanFocus = true;
			this.EntCodigo.Name = "EntCodigo";
			this.EntCodigo.IsEditable = false;
			this.EntCodigo.InvisibleChar = '•';
			this.vbox9.Add (this.EntCodigo);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.EntCodigo]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.EntCedula = new global::Gtk.Entry ();
			this.EntCedula.CanFocus = true;
			this.EntCedula.Name = "EntCedula";
			this.EntCedula.IsEditable = true;
			this.EntCedula.MaxLength = 9;
			this.EntCedula.InvisibleChar = '•';
			this.hbox15.Add (this.EntCedula);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.EntCedula]));
			w9.Position = 0;
			this.vbox9.Add (this.hbox15);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox15]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.EntNombre = new global::Gtk.Entry ();
			this.EntNombre.CanFocus = true;
			this.EntNombre.Name = "EntNombre";
			this.EntNombre.IsEditable = true;
			this.EntNombre.MaxLength = 30;
			this.EntNombre.InvisibleChar = '•';
			this.vbox9.Add (this.EntNombre);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.EntNombre]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.EntApellido = new global::Gtk.Entry ();
			this.EntApellido.CanFocus = true;
			this.EntApellido.Name = "EntApellido";
			this.EntApellido.IsEditable = true;
			this.EntApellido.MaxLength = 30;
			this.EntApellido.InvisibleChar = '•';
			this.vbox9.Add (this.EntApellido);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.EntApellido]));
			w12.Position = 4;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox14.Add (this.vbox9);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.vbox9]));
			w13.Position = 1;
			// Container child hbox14.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Homogeneous = true;
			this.vbox3.Spacing = 9;
			// Container child vbox3.Gtk.Box+BoxChild
			this.LblFechaIng = new global::Gtk.Label ();
			this.LblFechaIng.Name = "LblFechaIng";
			this.LblFechaIng.Xalign = 1F;
			this.LblFechaIng.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha de Ingreso:");
			this.vbox3.Add (this.LblFechaIng);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.LblFechaIng]));
			w14.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.LblUsuario = new global::Gtk.Label ();
			this.LblUsuario.Name = "LblUsuario";
			this.LblUsuario.Xalign = 1F;
			this.LblUsuario.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre de Usuario:");
			this.vbox3.Add (this.LblUsuario);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.LblUsuario]));
			w15.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.LblContrasena = new global::Gtk.Label ();
			this.LblContrasena.Name = "LblContrasena";
			this.LblContrasena.Xalign = 1F;
			this.LblContrasena.LabelProp = global::Mono.Unix.Catalog.GetString ("Contraseña:");
			this.vbox3.Add (this.LblContrasena);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.LblContrasena]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.LblCorreo = new global::Gtk.Label ();
			this.LblCorreo.Name = "LblCorreo";
			this.LblCorreo.Xalign = 1F;
			this.LblCorreo.LabelProp = global::Mono.Unix.Catalog.GetString ("        Correo Electrónico:");
			this.vbox3.Add (this.LblCorreo);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.LblCorreo]));
			w17.Position = 3;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.LblPista = new global::Gtk.Label ();
			this.LblPista.Name = "LblPista";
			this.LblPista.Xalign = 1F;
			this.LblPista.LabelProp = global::Mono.Unix.Catalog.GetString ("Pista de la Contraseña:");
			this.vbox3.Add (this.LblPista);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.LblPista]));
			w18.Position = 4;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox14.Add (this.vbox3);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.vbox3]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Homogeneous = true;
			this.vbox5.Spacing = 9;
			// Container child vbox5.Gtk.Box+BoxChild
			this.EntFechaIng = new global::Gtk.Entry ();
			this.EntFechaIng.CanFocus = true;
			this.EntFechaIng.Name = "EntFechaIng";
			this.EntFechaIng.IsEditable = false;
			this.EntFechaIng.InvisibleChar = '•';
			this.vbox5.Add (this.EntFechaIng);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.EntFechaIng]));
			w20.Position = 0;
			// Container child vbox5.Gtk.Box+BoxChild
			this.EntUsuario = new global::Gtk.Entry ();
			this.EntUsuario.CanFocus = true;
			this.EntUsuario.Name = "EntUsuario";
			this.EntUsuario.IsEditable = true;
			this.EntUsuario.MaxLength = 10;
			this.EntUsuario.InvisibleChar = '•';
			this.vbox5.Add (this.EntUsuario);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.EntUsuario]));
			w21.Position = 1;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.EntContrasena = new global::Gtk.Entry ();
			this.EntContrasena.CanFocus = true;
			this.EntContrasena.Name = "EntContrasena";
			this.EntContrasena.IsEditable = true;
			this.EntContrasena.MaxLength = 15;
			this.EntContrasena.Visibility = false;
			this.EntContrasena.InvisibleChar = '•';
			this.hbox3.Add (this.EntContrasena);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.EntContrasena]));
			w22.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.BtnVer = new global::Gtk.Button ();
			this.BtnVer.CanFocus = true;
			this.BtnVer.Name = "BtnVer";
			this.BtnVer.UseUnderline = true;
			global::Gtk.Image w23 = new global::Gtk.Image ();
			w23.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Menu);
			this.BtnVer.Image = w23;
			this.hbox3.Add (this.BtnVer);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.BtnVer]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.hbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox3]));
			w25.Position = 0;
			this.vbox5.Add (this.hbox1);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox1]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.EntEmail = new global::Gtk.Entry ();
			this.EntEmail.CanFocus = true;
			this.EntEmail.Name = "EntEmail";
			this.EntEmail.IsEditable = true;
			this.EntEmail.MaxLength = 45;
			this.EntEmail.InvisibleChar = '•';
			this.vbox5.Add (this.EntEmail);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.EntEmail]));
			w27.Position = 3;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.EntPista = new global::Gtk.Entry ();
			this.EntPista.CanFocus = true;
			this.EntPista.Name = "EntPista";
			this.EntPista.IsEditable = true;
			this.EntPista.MaxLength = 45;
			this.EntPista.InvisibleChar = '•';
			this.vbox5.Add (this.EntPista);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.EntPista]));
			w28.Position = 4;
			w28.Expand = false;
			w28.Fill = false;
			this.hbox14.Add (this.vbox5);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.vbox5]));
			w29.Position = 3;
			this.vbox2.Add (this.hbox14);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox14]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.LblTipoUsuario = new global::Gtk.Label ();
			this.LblTipoUsuario.Name = "LblTipoUsuario";
			this.LblTipoUsuario.Xalign = 1F;
			this.LblTipoUsuario.LabelProp = global::Mono.Unix.Catalog.GetString ("                 Tipo de Usuario:");
			this.hbox2.Add (this.LblTipoUsuario);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.LblTipoUsuario]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Homogeneous = true;
			this.vbox7.Spacing = -25;
			// Container child vbox7.Gtk.Box+BoxChild
			this.RbAdministrador = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Administrador del Sistema"));
			this.RbAdministrador.CanFocus = true;
			this.RbAdministrador.Name = "RbAdministrador";
			this.RbAdministrador.Active = true;
			this.RbAdministrador.DrawIndicator = true;
			this.RbAdministrador.UseUnderline = true;
			this.RbAdministrador.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox7.Add (this.RbAdministrador);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.RbAdministrador]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.RbVendedor = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Vendedor"));
			this.RbVendedor.CanFocus = true;
			this.RbVendedor.Name = "RbVendedor";
			this.RbVendedor.DrawIndicator = true;
			this.RbVendedor.UseUnderline = true;
			this.RbVendedor.Group = this.RbAdministrador.Group;
			this.vbox7.Add (this.RbVendedor);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.RbVendedor]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.RbActualizador = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Administrador de la Bases de Datos"));
			this.RbActualizador.CanFocus = true;
			this.RbActualizador.Name = "RbActualizador";
			this.RbActualizador.DrawIndicator = true;
			this.RbActualizador.UseUnderline = true;
			this.RbActualizador.Group = this.RbAdministrador.Group;
			this.vbox7.Add (this.RbActualizador);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.RbActualizador]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			this.hbox2.Add (this.vbox7);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox7]));
			w35.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Homogeneous = true;
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.BtnIncluir = new global::Gtk.Button ();
			this.BtnIncluir.WidthRequest = 195;
			this.BtnIncluir.HeightRequest = 40;
			this.BtnIncluir.Sensitive = false;
			this.BtnIncluir.CanFocus = true;
			this.BtnIncluir.Name = "BtnIncluir";
			this.BtnIncluir.UseUnderline = true;
			this.BtnIncluir.Label = global::Mono.Unix.Catalog.GetString ("Incluir");
			this.vbox6.Add (this.BtnIncluir);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.BtnIncluir]));
			w36.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.BtnModificar = new global::Gtk.Button ();
			this.BtnModificar.Sensitive = false;
			this.BtnModificar.CanFocus = true;
			this.BtnModificar.Name = "BtnModificar";
			this.BtnModificar.UseUnderline = true;
			this.BtnModificar.Label = global::Mono.Unix.Catalog.GetString ("Modificar");
			this.vbox6.Add (this.BtnModificar);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.BtnModificar]));
			w37.Position = 1;
			// Container child vbox6.Gtk.Box+BoxChild
			this.BtnEliminar = new global::Gtk.Button ();
			this.BtnEliminar.Sensitive = false;
			this.BtnEliminar.CanFocus = true;
			this.BtnEliminar.Name = "BtnEliminar";
			this.BtnEliminar.UseUnderline = true;
			this.BtnEliminar.Label = global::Mono.Unix.Catalog.GetString ("Eliminar");
			this.vbox6.Add (this.BtnEliminar);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.BtnEliminar]));
			w38.Position = 2;
			this.hbox2.Add (this.vbox6);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox6]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Homogeneous = true;
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox12.Add (this.fixed1);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.fixed1]));
			w41.Position = 0;
			this.vbox2.Add (this.hbox12);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox12]));
			w42.Position = 2;
			w42.Expand = false;
			w42.Fill = false;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w43.Position = 0;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			this.GtkAlignment1.BorderWidth = ((uint)(6));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TvUsuarios = new global::Gtk.TreeView ();
			this.TvUsuarios.CanFocus = true;
			this.TvUsuarios.Name = "TvUsuarios";
			this.GtkScrolledWindow.Add (this.TvUsuarios);
			this.GtkAlignment1.Add (this.GtkScrolledWindow);
			this.frame2.Add (this.GtkAlignment1);
			this.LblUsuariosSistema = new global::Gtk.Label ();
			this.LblUsuariosSistema.Name = "LblUsuariosSistema";
			this.LblUsuariosSistema.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Usuarios registrados en el sistema</b>");
			this.LblUsuariosSistema.UseMarkup = true;
			this.frame2.LabelWidget = this.LblUsuariosSistema;
			this.vbox1.Add (this.frame2);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame2]));
			w47.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Homogeneous = true;
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.BtnLimpiar = new global::Gtk.Button ();
			this.BtnLimpiar.HeightRequest = 30;
			this.BtnLimpiar.Sensitive = false;
			this.BtnLimpiar.CanFocus = true;
			this.BtnLimpiar.Name = "BtnLimpiar";
			this.BtnLimpiar.UseUnderline = true;
			this.BtnLimpiar.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
			this.hbox13.Add (this.BtnLimpiar);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.BtnLimpiar]));
			w48.Position = 0;
			// Container child hbox13.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox13.Add (this.fixed2);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.fixed2]));
			w49.Position = 1;
			// Container child hbox13.Gtk.Box+BoxChild
			this.BtnCancelar = new global::Gtk.Button ();
			this.BtnCancelar.CanFocus = true;
			this.BtnCancelar.Name = "BtnCancelar";
			this.BtnCancelar.UseUnderline = true;
			this.BtnCancelar.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox13.Add (this.BtnCancelar);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.BtnCancelar]));
			w50.Position = 2;
			// Container child hbox13.Gtk.Box+BoxChild
			this.BtnSalir = new global::Gtk.Button ();
			this.BtnSalir.WidthRequest = 0;
			this.BtnSalir.HeightRequest = 40;
			this.BtnSalir.CanFocus = true;
			this.BtnSalir.Name = "BtnSalir";
			this.BtnSalir.UseUnderline = true;
			this.BtnSalir.Label = global::Mono.Unix.Catalog.GetString ("Salir");
			this.hbox13.Add (this.BtnSalir);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.BtnSalir]));
			w51.Position = 3;
			this.vbox1.Add (this.hbox13);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox13]));
			w52.Position = 2;
			w52.Expand = false;
			w52.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w53.Position = 3;
			w53.Expand = false;
			w53.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.LblFechaHora = new global::Gtk.Label ();
			this.LblFechaHora.Name = "LblFechaHora";
			this.LblFechaHora.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha y Hora");
			this.GtkAlignment2.Add (this.LblFechaHora);
			this.frame1.Add (this.GtkAlignment2);
			this.vbox1.Add (this.frame1);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
			w56.Position = 4;
			w56.Expand = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 826;
			this.DefaultHeight = 645;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.EntCodigoReg.Changed += new global::System.EventHandler (this.OnEntCodigoRegChanged);
			this.EntCedula.Changed += new global::System.EventHandler (this.OnEntCedulaChanged);
			this.EntNombre.Changed += new global::System.EventHandler (this.OnEntNombreChanged);
			this.EntApellido.Changed += new global::System.EventHandler (this.OnEntApellidoChanged);
			this.EntUsuario.Changed += new global::System.EventHandler (this.OnEntUsuarioChanged);
			this.BtnVer.Clicked += new global::System.EventHandler (this.OnBtnVerClicked);
			this.RbAdministrador.Clicked += new global::System.EventHandler (this.OnRbAdministradorClicked);
			this.RbVendedor.Clicked += new global::System.EventHandler (this.OnRbVendedorClicked);
			this.RbActualizador.Clicked += new global::System.EventHandler (this.OnRbActualizadorClicked);
			this.BtnIncluir.Clicked += new global::System.EventHandler (this.OnBtnIncluirClicked);
			this.BtnModificar.Clicked += new global::System.EventHandler (this.OnBtnModificarClicked);
			this.BtnEliminar.Clicked += new global::System.EventHandler (this.OnBtnEliminarClicked);
			this.TvUsuarios.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTvUsuariosRowActivated);
			this.BtnLimpiar.Clicked += new global::System.EventHandler (this.OnBtnLimpiarClicked);
			this.BtnCancelar.Clicked += new global::System.EventHandler (this.OnBtnCancelarClicked);
			this.BtnSalir.Clicked += new global::System.EventHandler (this.OnBtnSalirClicked);
		}
	}
}
