
// This file has been generated by the GUI designer. Do not modify.
namespace WhiteRose
{
	public partial class VntConsultarFactura
	{
		private global::Gtk.VBox vbox10;
		
		private global::Gtk.HBox hbox25;
		
		private global::Gtk.Label LblNroFact;
		
		private global::Gtk.Entry EntNroFact;
		
		private global::Gtk.Button BtnBuscar;
		
		private global::Gtk.HSeparator hseparator2;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label LblFechaE;
		
		private global::Gtk.Entry EntFechaE;
		
		private global::Gtk.Label LblHoraE;
		
		private global::Gtk.Entry EntHoraE;
		
		private global::Gtk.Label LblFecha;
		
		private global::Gtk.Label LblTipoV;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.RadioButton RbDetal;
		
		private global::Gtk.RadioButton RbMayor;
		
		private global::Gtk.Frame frame8;
		
		private global::Gtk.Alignment GtkAlignment3;
		
		private global::Gtk.VBox vbox14;
		
		private global::Gtk.HBox hbox23;
		
		private global::Gtk.Label LblRif;
		
		private global::Gtk.Entry EntRifCliente;
		
		private global::Gtk.HBox hbox24;
		
		private global::Gtk.Label LblNombreCliente;
		
		private global::Gtk.Entry EntNombreCliente;
		
		private global::Gtk.HBox hbox22;
		
		private global::Gtk.Label LblDireccionCliente;
		
		private global::Gtk.Entry EntDireccionCliente;
		
		private global::Gtk.Label LblTelefono;
		
		private global::Gtk.Entry EntTlfCliente;
		
		private global::Gtk.Label LblIdCliente;
		
		private global::Gtk.Frame frame7;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView TvServiciosPagados;
		
		private global::Gtk.Label LblServiciosAPagar;
		
		private global::Gtk.Frame frame6;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.Label LblSubtotal;
		
		private global::Gtk.Label LblPorcDesc;
		
		private global::Gtk.Label LblBaseImponible;
		
		private global::Gtk.Fixed fixed9;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.Entry EntSubtotal;
		
		private global::Gtk.Entry EntPorcDesc;
		
		private global::Gtk.Entry EntBaseImp;
		
		private global::Gtk.Fixed fixed10;
		
		private global::Gtk.Fixed fixed11;
		
		private global::Gtk.VBox vbox16;
		
		private global::Gtk.Fixed fixed5;
		
		private global::Gtk.Label LblMonto;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label LblIva;
		
		private global::Gtk.Entry EntIva1;
		
		private global::Gtk.Label LblIva2;
		
		private global::Gtk.Label LblMontosPagar1;
		
		private global::Gtk.VBox vbox17;
		
		private global::Gtk.Fixed fixed6;
		
		private global::Gtk.Entry EntMontoDesc;
		
		private global::Gtk.Entry EntIva;
		
		private global::Gtk.Entry EntTotalPagar;
		
		private global::Gtk.Label LblMontosPagar;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Button BtnCancelar;
		
		private global::Gtk.Button BtnSalir;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.Label LblFechaHora;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WhiteRose.VntConsultarFactura
			this.Name = "WhiteRose.VntConsultarFactura";
			this.Title = global::Mono.Unix.Catalog.GetString ("Consultar Factura");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(6));
			// Container child WhiteRose.VntConsultarFactura.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox25 = new global::Gtk.HBox ();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 6;
			// Container child hbox25.Gtk.Box+BoxChild
			this.LblNroFact = new global::Gtk.Label ();
			this.LblNroFact.Name = "LblNroFact";
			this.LblNroFact.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Número de Factura:</b>");
			this.LblNroFact.UseMarkup = true;
			this.hbox25.Add (this.LblNroFact);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.LblNroFact]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.EntNroFact = new global::Gtk.Entry ();
			this.EntNroFact.CanFocus = true;
			this.EntNroFact.Name = "EntNroFact";
			this.EntNroFact.IsEditable = true;
			this.EntNroFact.MaxLength = 5;
			this.EntNroFact.InvisibleChar = '•';
			this.hbox25.Add (this.EntNroFact);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.EntNroFact]));
			w2.Position = 1;
			w2.Expand = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.BtnBuscar = new global::Gtk.Button ();
			this.BtnBuscar.CanFocus = true;
			this.BtnBuscar.Name = "BtnBuscar";
			this.BtnBuscar.UseUnderline = true;
			this.BtnBuscar.BorderWidth = ((uint)(3));
			this.BtnBuscar.Label = global::Mono.Unix.Catalog.GetString ("Buscar");
			this.hbox25.Add (this.BtnBuscar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.BtnBuscar]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox10.Add (this.hbox25);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox25]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox10.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hseparator2]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			this.GtkAlignment4.BorderWidth = ((uint)(6));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.LblFechaE = new global::Gtk.Label ();
			this.LblFechaE.Name = "LblFechaE";
			this.LblFechaE.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha: ");
			this.hbox3.Add (this.LblFechaE);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.LblFechaE]));
			w6.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.EntFechaE = new global::Gtk.Entry ();
			this.EntFechaE.CanFocus = true;
			this.EntFechaE.Name = "EntFechaE";
			this.EntFechaE.IsEditable = true;
			this.EntFechaE.InvisibleChar = '●';
			this.hbox3.Add (this.EntFechaE);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.EntFechaE]));
			w7.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.LblHoraE = new global::Gtk.Label ();
			this.LblHoraE.Name = "LblHoraE";
			this.LblHoraE.LabelProp = global::Mono.Unix.Catalog.GetString ("Hora: ");
			this.hbox3.Add (this.LblHoraE);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.LblHoraE]));
			w8.Position = 2;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.EntHoraE = new global::Gtk.Entry ();
			this.EntHoraE.CanFocus = true;
			this.EntHoraE.Name = "EntHoraE";
			this.EntHoraE.IsEditable = true;
			this.EntHoraE.InvisibleChar = '●';
			this.hbox3.Add (this.EntHoraE);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.EntHoraE]));
			w9.Position = 3;
			this.GtkAlignment4.Add (this.hbox3);
			this.frame2.Add (this.GtkAlignment4);
			this.LblFecha = new global::Gtk.Label ();
			this.LblFecha.Name = "LblFecha";
			this.LblFecha.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Fecha de Emisión</b>");
			this.LblFecha.UseMarkup = true;
			this.frame2.LabelWidget = this.LblFecha;
			this.hbox2.Add (this.frame2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.frame2]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.LblTipoV = new global::Gtk.Label ();
			this.LblTipoV.Name = "LblTipoV";
			this.LblTipoV.LabelProp = global::Mono.Unix.Catalog.GetString ("Tipo de Venta:");
			this.hbox2.Add (this.LblTipoV);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.LblTipoV]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.RbDetal = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Detal"));
			this.RbDetal.Sensitive = false;
			this.RbDetal.CanFocus = true;
			this.RbDetal.Name = "RbDetal";
			this.RbDetal.DrawIndicator = true;
			this.RbDetal.UseUnderline = true;
			this.RbDetal.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox1.Add (this.RbDetal);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.RbDetal]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.RbMayor = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Mayor"));
			this.RbMayor.Sensitive = false;
			this.RbMayor.CanFocus = true;
			this.RbMayor.Name = "RbMayor";
			this.RbMayor.DrawIndicator = true;
			this.RbMayor.UseUnderline = true;
			this.RbMayor.Group = this.RbDetal.Group;
			this.vbox1.Add (this.RbMayor);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.RbMayor]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.hbox2.Add (this.vbox1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox1]));
			w16.Position = 2;
			this.vbox10.Add (this.hbox2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox2]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.frame8 = new global::Gtk.Frame ();
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame8.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			this.GtkAlignment3.BorderWidth = ((uint)(6));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox ();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.LblRif = new global::Gtk.Label ();
			this.LblRif.Name = "LblRif";
			this.LblRif.Xalign = 1F;
			this.LblRif.LabelProp = global::Mono.Unix.Catalog.GetString ("Rif:");
			this.hbox23.Add (this.LblRif);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.LblRif]));
			w18.Position = 0;
			w18.Expand = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.EntRifCliente = new global::Gtk.Entry ();
			this.EntRifCliente.CanFocus = true;
			this.EntRifCliente.Name = "EntRifCliente";
			this.EntRifCliente.IsEditable = false;
			this.EntRifCliente.InvisibleChar = '•';
			this.hbox23.Add (this.EntRifCliente);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.EntRifCliente]));
			w19.Position = 1;
			w19.Expand = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox ();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.LblNombreCliente = new global::Gtk.Label ();
			this.LblNombreCliente.Name = "LblNombreCliente";
			this.LblNombreCliente.Xalign = 1F;
			this.LblNombreCliente.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre:");
			this.hbox24.Add (this.LblNombreCliente);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.LblNombreCliente]));
			w20.Position = 0;
			w20.Expand = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.EntNombreCliente = new global::Gtk.Entry ();
			this.EntNombreCliente.CanFocus = true;
			this.EntNombreCliente.Name = "EntNombreCliente";
			this.EntNombreCliente.IsEditable = false;
			this.EntNombreCliente.InvisibleChar = '•';
			this.hbox24.Add (this.EntNombreCliente);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.EntNombreCliente]));
			w21.Position = 1;
			this.hbox23.Add (this.hbox24);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.hbox24]));
			w22.Position = 2;
			this.vbox14.Add (this.hbox23);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox23]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox ();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.LblDireccionCliente = new global::Gtk.Label ();
			this.LblDireccionCliente.Name = "LblDireccionCliente";
			this.LblDireccionCliente.Xalign = 1F;
			this.LblDireccionCliente.LabelProp = global::Mono.Unix.Catalog.GetString ("Dirección:");
			this.hbox22.Add (this.LblDireccionCliente);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.LblDireccionCliente]));
			w24.Position = 0;
			w24.Expand = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.EntDireccionCliente = new global::Gtk.Entry ();
			this.EntDireccionCliente.CanFocus = true;
			this.EntDireccionCliente.Name = "EntDireccionCliente";
			this.EntDireccionCliente.IsEditable = false;
			this.EntDireccionCliente.InvisibleChar = '•';
			this.hbox22.Add (this.EntDireccionCliente);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.EntDireccionCliente]));
			w25.Position = 1;
			// Container child hbox22.Gtk.Box+BoxChild
			this.LblTelefono = new global::Gtk.Label ();
			this.LblTelefono.Name = "LblTelefono";
			this.LblTelefono.Xalign = 1F;
			this.LblTelefono.LabelProp = global::Mono.Unix.Catalog.GetString ("Teléfono:");
			this.hbox22.Add (this.LblTelefono);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.LblTelefono]));
			w26.Position = 2;
			w26.Expand = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.EntTlfCliente = new global::Gtk.Entry ();
			this.EntTlfCliente.CanFocus = true;
			this.EntTlfCliente.Name = "EntTlfCliente";
			this.EntTlfCliente.IsEditable = false;
			this.EntTlfCliente.InvisibleChar = '•';
			this.hbox22.Add (this.EntTlfCliente);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.EntTlfCliente]));
			w27.Position = 3;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox14.Add (this.hbox22);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox22]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.GtkAlignment3.Add (this.vbox14);
			this.frame8.Add (this.GtkAlignment3);
			this.LblIdCliente = new global::Gtk.Label ();
			this.LblIdCliente.Name = "LblIdCliente";
			this.LblIdCliente.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Identificación del Cliente</b>");
			this.LblIdCliente.UseMarkup = true;
			this.frame8.LabelWidget = this.LblIdCliente;
			this.vbox10.Add (this.frame8);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.frame8]));
			w31.Position = 3;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.frame7 = new global::Gtk.Frame ();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			this.GtkAlignment2.BorderWidth = ((uint)(6));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TvServiciosPagados = new global::Gtk.TreeView ();
			this.TvServiciosPagados.CanFocus = true;
			this.TvServiciosPagados.Name = "TvServiciosPagados";
			this.GtkScrolledWindow.Add (this.TvServiciosPagados);
			this.GtkAlignment2.Add (this.GtkScrolledWindow);
			this.frame7.Add (this.GtkAlignment2);
			this.LblServiciosAPagar = new global::Gtk.Label ();
			this.LblServiciosAPagar.Name = "LblServiciosAPagar";
			this.LblServiciosAPagar.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Servicios Pagados</b>");
			this.LblServiciosAPagar.UseMarkup = true;
			this.frame7.LabelWidget = this.LblServiciosAPagar;
			this.vbox10.Add (this.frame7);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.frame7]));
			w35.Position = 4;
			// Container child vbox10.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			this.GtkAlignment1.BorderWidth = ((uint)(6));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Homogeneous = true;
			this.vbox5.Spacing = 9;
			// Container child vbox5.Gtk.Box+BoxChild
			this.LblSubtotal = new global::Gtk.Label ();
			this.LblSubtotal.Name = "LblSubtotal";
			this.LblSubtotal.Xalign = 1F;
			this.LblSubtotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Subtotal:");
			this.vbox5.Add (this.LblSubtotal);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.LblSubtotal]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.LblPorcDesc = new global::Gtk.Label ();
			this.LblPorcDesc.Name = "LblPorcDesc";
			this.LblPorcDesc.Xalign = 1F;
			this.LblPorcDesc.LabelProp = global::Mono.Unix.Catalog.GetString ("% Descuento:");
			this.vbox5.Add (this.LblPorcDesc);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.LblPorcDesc]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.LblBaseImponible = new global::Gtk.Label ();
			this.LblBaseImponible.Name = "LblBaseImponible";
			this.LblBaseImponible.Xalign = 1F;
			this.LblBaseImponible.LabelProp = global::Mono.Unix.Catalog.GetString ("Base Imponible:");
			this.vbox5.Add (this.LblBaseImponible);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.LblBaseImponible]));
			w38.Position = 2;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.fixed9 = new global::Gtk.Fixed ();
			this.fixed9.Name = "fixed9";
			this.fixed9.HasWindow = false;
			this.vbox5.Add (this.fixed9);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.fixed9]));
			w39.PackType = ((global::Gtk.PackType)(1));
			w39.Position = 3;
			this.hbox4.Add (this.vbox5);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox5]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Homogeneous = true;
			this.vbox6.Spacing = 9;
			// Container child vbox6.Gtk.Box+BoxChild
			this.EntSubtotal = new global::Gtk.Entry ();
			this.EntSubtotal.CanFocus = true;
			this.EntSubtotal.Name = "EntSubtotal";
			this.EntSubtotal.IsEditable = false;
			this.EntSubtotal.InvisibleChar = '•';
			this.vbox6.Add (this.EntSubtotal);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.EntSubtotal]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.EntPorcDesc = new global::Gtk.Entry ();
			this.EntPorcDesc.CanFocus = true;
			this.EntPorcDesc.Name = "EntPorcDesc";
			this.EntPorcDesc.Text = global::Mono.Unix.Catalog.GetString ("0");
			this.EntPorcDesc.IsEditable = true;
			this.EntPorcDesc.MaxLength = 2;
			this.EntPorcDesc.InvisibleChar = '•';
			this.vbox6.Add (this.EntPorcDesc);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.EntPorcDesc]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.EntBaseImp = new global::Gtk.Entry ();
			this.EntBaseImp.CanFocus = true;
			this.EntBaseImp.Name = "EntBaseImp";
			this.EntBaseImp.IsEditable = false;
			this.EntBaseImp.InvisibleChar = '•';
			this.vbox6.Add (this.EntBaseImp);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.EntBaseImp]));
			w43.Position = 2;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.fixed10 = new global::Gtk.Fixed ();
			this.fixed10.Name = "fixed10";
			this.fixed10.HasWindow = false;
			this.vbox6.Add (this.fixed10);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.fixed10]));
			w44.Position = 3;
			this.hbox4.Add (this.vbox6);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox6]));
			w45.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.fixed11 = new global::Gtk.Fixed ();
			this.fixed11.Name = "fixed11";
			this.fixed11.HasWindow = false;
			this.hbox4.Add (this.fixed11);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.fixed11]));
			w46.Position = 2;
			w46.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox16 = new global::Gtk.VBox ();
			this.vbox16.Name = "vbox16";
			this.vbox16.Homogeneous = true;
			this.vbox16.Spacing = 9;
			// Container child vbox16.Gtk.Box+BoxChild
			this.fixed5 = new global::Gtk.Fixed ();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			this.vbox16.Add (this.fixed5);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.fixed5]));
			w47.Position = 0;
			// Container child vbox16.Gtk.Box+BoxChild
			this.LblMonto = new global::Gtk.Label ();
			this.LblMonto.Name = "LblMonto";
			this.LblMonto.Xalign = 1F;
			this.LblMonto.LabelProp = global::Mono.Unix.Catalog.GetString ("Monto del Descuento:");
			this.vbox16.Add (this.LblMonto);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.LblMonto]));
			w48.Position = 1;
			w48.Expand = false;
			w48.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.LblIva = new global::Gtk.Label ();
			this.LblIva.WidthRequest = 83;
			this.LblIva.Name = "LblIva";
			this.LblIva.Xalign = 1F;
			this.LblIva.LabelProp = global::Mono.Unix.Catalog.GetString ("IVA (");
			this.hbox5.Add (this.LblIva);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.LblIva]));
			w49.Position = 0;
			w49.Expand = false;
			w49.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.EntIva1 = new global::Gtk.Entry ();
			this.EntIva1.WidthRequest = 30;
			this.EntIva1.CanFocus = true;
			this.EntIva1.Name = "EntIva1";
			this.EntIva1.Text = global::Mono.Unix.Catalog.GetString ("12");
			this.EntIva1.IsEditable = true;
			this.EntIva1.MaxLength = 2;
			this.EntIva1.InvisibleChar = '•';
			this.hbox5.Add (this.EntIva1);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.EntIva1]));
			w50.Position = 1;
			w50.Expand = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.LblIva2 = new global::Gtk.Label ();
			this.LblIva2.Name = "LblIva2";
			this.LblIva2.Xalign = 1F;
			this.LblIva2.LabelProp = global::Mono.Unix.Catalog.GetString ("%):");
			this.hbox5.Add (this.LblIva2);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.LblIva2]));
			w51.Position = 2;
			w51.Expand = false;
			w51.Fill = false;
			this.vbox16.Add (this.hbox5);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.hbox5]));
			w52.Position = 2;
			// Container child vbox16.Gtk.Box+BoxChild
			this.LblMontosPagar1 = new global::Gtk.Label ();
			this.LblMontosPagar1.Name = "LblMontosPagar1";
			this.LblMontosPagar1.Xalign = 1F;
			this.LblMontosPagar1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Total a Pagar:</b>");
			this.LblMontosPagar1.UseMarkup = true;
			this.vbox16.Add (this.LblMontosPagar1);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.LblMontosPagar1]));
			w53.Position = 3;
			w53.Expand = false;
			w53.Fill = false;
			this.hbox4.Add (this.vbox16);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox16]));
			w54.Position = 3;
			w54.Expand = false;
			w54.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox ();
			this.vbox17.Name = "vbox17";
			this.vbox17.Homogeneous = true;
			this.vbox17.Spacing = 9;
			// Container child vbox17.Gtk.Box+BoxChild
			this.fixed6 = new global::Gtk.Fixed ();
			this.fixed6.Name = "fixed6";
			this.fixed6.HasWindow = false;
			this.vbox17.Add (this.fixed6);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.fixed6]));
			w55.Position = 0;
			// Container child vbox17.Gtk.Box+BoxChild
			this.EntMontoDesc = new global::Gtk.Entry ();
			this.EntMontoDesc.CanFocus = true;
			this.EntMontoDesc.Name = "EntMontoDesc";
			this.EntMontoDesc.IsEditable = false;
			this.EntMontoDesc.InvisibleChar = '•';
			this.vbox17.Add (this.EntMontoDesc);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.EntMontoDesc]));
			w56.Position = 1;
			w56.Expand = false;
			w56.Fill = false;
			// Container child vbox17.Gtk.Box+BoxChild
			this.EntIva = new global::Gtk.Entry ();
			this.EntIva.CanFocus = true;
			this.EntIva.Name = "EntIva";
			this.EntIva.IsEditable = false;
			this.EntIva.InvisibleChar = '•';
			this.vbox17.Add (this.EntIva);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.EntIva]));
			w57.Position = 2;
			w57.Expand = false;
			w57.Fill = false;
			// Container child vbox17.Gtk.Box+BoxChild
			this.EntTotalPagar = new global::Gtk.Entry ();
			this.EntTotalPagar.CanFocus = true;
			this.EntTotalPagar.Name = "EntTotalPagar";
			this.EntTotalPagar.IsEditable = false;
			this.EntTotalPagar.InvisibleChar = '•';
			this.vbox17.Add (this.EntTotalPagar);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.EntTotalPagar]));
			w58.Position = 3;
			w58.Expand = false;
			w58.Fill = false;
			this.hbox4.Add (this.vbox17);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox17]));
			w59.Position = 4;
			this.GtkAlignment1.Add (this.hbox4);
			this.frame6.Add (this.GtkAlignment1);
			this.LblMontosPagar = new global::Gtk.Label ();
			this.LblMontosPagar.Name = "LblMontosPagar";
			this.LblMontosPagar.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Descripción del Monto a Pagar</b>");
			this.LblMontosPagar.UseMarkup = true;
			this.frame6.LabelWidget = this.LblMontosPagar;
			this.vbox10.Add (this.frame6);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.frame6]));
			w62.Position = 5;
			w62.Expand = false;
			w62.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixed1]));
			w63.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BtnCancelar = new global::Gtk.Button ();
			this.BtnCancelar.CanFocus = true;
			this.BtnCancelar.Name = "BtnCancelar";
			this.BtnCancelar.UseUnderline = true;
			this.BtnCancelar.BorderWidth = ((uint)(3));
			this.BtnCancelar.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox1.Add (this.BtnCancelar);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.BtnCancelar]));
			w64.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BtnSalir = new global::Gtk.Button ();
			this.BtnSalir.CanFocus = true;
			this.BtnSalir.Name = "BtnSalir";
			this.BtnSalir.UseUnderline = true;
			this.BtnSalir.BorderWidth = ((uint)(3));
			this.BtnSalir.Label = global::Mono.Unix.Catalog.GetString ("Salir");
			this.hbox1.Add (this.BtnSalir);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.BtnSalir]));
			w65.Position = 2;
			this.vbox10.Add (this.hbox1);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox1]));
			w66.Position = 6;
			w66.Expand = false;
			w66.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox10.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hseparator1]));
			w67.Position = 7;
			w67.Expand = false;
			w67.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.LblFechaHora = new global::Gtk.Label ();
			this.LblFechaHora.Name = "LblFechaHora";
			this.LblFechaHora.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha y Hora");
			this.GtkAlignment.Add (this.LblFechaHora);
			this.frame1.Add (this.GtkAlignment);
			this.vbox10.Add (this.frame1);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.frame1]));
			w70.Position = 8;
			w70.Expand = false;
			w70.Fill = false;
			this.Add (this.vbox10);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 661;
			this.DefaultHeight = 679;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.EntNroFact.Changed += new global::System.EventHandler (this.OnEntNroFactChanged);
			this.BtnBuscar.Clicked += new global::System.EventHandler (this.OnBtnBuscarClicked);
			this.BtnCancelar.Clicked += new global::System.EventHandler (this.OnBtnCancelarClicked);
			this.BtnSalir.Clicked += new global::System.EventHandler (this.OnBtnSalirClicked);
		}
	}
}
