
// This file has been generated by the GUI designer. Do not modify.
namespace WhiteRose
{
	public partial class VntActualizarCliente
	{
		private global::Gtk.Table table2;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.TreeView TvClientes;
		
		private global::Gtk.Label LblClientes;
		
		private global::Gtk.Table table3;
		
		private global::Gtk.Button BtnCancelar;
		
		private global::Gtk.Button BtnLimpiar;
		
		private global::Gtk.Button BtnSalir;
		
		private global::Gtk.Fixed fixed3;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.Label LblRif;
		
		private global::Gtk.Label LblNombre;
		
		private global::Gtk.Label LblDireccion;
		
		private global::Gtk.Label LblTelefono;
		
		private global::Gtk.VBox vbox8;
		
		private global::Gtk.Entry EntRif;
		
		private global::Gtk.Entry EntNombre;
		
		private global::Gtk.Entry EntDireccion;
		
		private global::Gtk.Entry EntTelefono;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Button BtnEliminar;
		
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Button BtnModificar;
		
		private global::Gtk.Button BtnIncluir;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.HSeparator hseparator3;
		
		private global::Gtk.Frame frame4;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.Label LblFechaHora;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WhiteRose.VntActualizarCliente
			this.Name = "WhiteRose.VntActualizarCliente";
			this.Title = global::Mono.Unix.Catalog.GetString ("Actualizar Clientes");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(6));
			// Container child WhiteRose.VntActualizarCliente.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(4)), ((uint)(1)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(13));
			this.table2.ColumnSpacing = ((uint)(25));
			this.table2.BorderWidth = ((uint)(8));
			// Container child table2.Gtk.Table+TableChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(1));
			this.frame2.BorderWidth = ((uint)(3));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.TvClientes = new global::Gtk.TreeView ();
			this.TvClientes.CanFocus = true;
			this.TvClientes.Name = "TvClientes";
			this.TvClientes.Reorderable = true;
			this.scrolledwindow1.Add (this.TvClientes);
			this.GtkAlignment.Add (this.scrolledwindow1);
			this.frame2.Add (this.GtkAlignment);
			this.LblClientes = new global::Gtk.Label ();
			this.LblClientes.Name = "LblClientes";
			this.LblClientes.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Clientes Actuales</b>");
			this.LblClientes.UseMarkup = true;
			this.frame2.LabelWidget = this.LblClientes;
			this.table2.Add (this.frame2);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.frame2]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			// Container child table2.Gtk.Table+TableChild
			this.table3 = new global::Gtk.Table (((uint)(1)), ((uint)(4)), true);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.BtnCancelar = new global::Gtk.Button ();
			this.BtnCancelar.CanFocus = true;
			this.BtnCancelar.Name = "BtnCancelar";
			this.BtnCancelar.UseUnderline = true;
			this.BtnCancelar.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.table3.Add (this.BtnCancelar);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3 [this.BtnCancelar]));
			w5.LeftAttach = ((uint)(2));
			w5.RightAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.BtnLimpiar = new global::Gtk.Button ();
			this.BtnLimpiar.HeightRequest = 30;
			this.BtnLimpiar.CanFocus = true;
			this.BtnLimpiar.Name = "BtnLimpiar";
			this.BtnLimpiar.UseUnderline = true;
			this.BtnLimpiar.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
			this.table3.Add (this.BtnLimpiar);
			// Container child table3.Gtk.Table+TableChild
			this.BtnSalir = new global::Gtk.Button ();
			this.BtnSalir.CanFocus = true;
			this.BtnSalir.Name = "BtnSalir";
			this.BtnSalir.UseUnderline = true;
			this.BtnSalir.Label = global::Mono.Unix.Catalog.GetString ("Salir");
			this.table3.Add (this.BtnSalir);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3 [this.BtnSalir]));
			w7.LeftAttach = ((uint)(3));
			w7.RightAttach = ((uint)(4));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.table3.Add (this.fixed3);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed3]));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table2.Add (this.table3);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.table3]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			this.hbox5.BorderWidth = ((uint)(3));
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Homogeneous = true;
			this.vbox6.Spacing = 15;
			// Container child vbox6.Gtk.Box+BoxChild
			this.LblRif = new global::Gtk.Label ();
			this.LblRif.Name = "LblRif";
			this.LblRif.Xalign = 1F;
			this.LblRif.LabelProp = global::Mono.Unix.Catalog.GetString ("RIF:");
			this.vbox6.Add (this.LblRif);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.LblRif]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.LblNombre = new global::Gtk.Label ();
			this.LblNombre.Name = "LblNombre";
			this.LblNombre.Xalign = 1F;
			this.LblNombre.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre:");
			this.vbox6.Add (this.LblNombre);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.LblNombre]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.LblDireccion = new global::Gtk.Label ();
			this.LblDireccion.Name = "LblDireccion";
			this.LblDireccion.Xalign = 1F;
			this.LblDireccion.LabelProp = global::Mono.Unix.Catalog.GetString ("Dirección:");
			this.vbox6.Add (this.LblDireccion);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.LblDireccion]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.LblTelefono = new global::Gtk.Label ();
			this.LblTelefono.Name = "LblTelefono";
			this.LblTelefono.LabelProp = global::Mono.Unix.Catalog.GetString ("  Teléfono:");
			this.vbox6.Add (this.LblTelefono);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.LblTelefono]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			this.hbox5.Add (this.vbox6);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox6]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Homogeneous = true;
			this.vbox8.Spacing = 15;
			// Container child vbox8.Gtk.Box+BoxChild
			this.EntRif = new global::Gtk.Entry ();
			this.EntRif.CanFocus = true;
			this.EntRif.Name = "EntRif";
			this.EntRif.IsEditable = true;
			this.EntRif.MaxLength = 15;
			this.EntRif.InvisibleChar = '•';
			this.vbox8.Add (this.EntRif);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.EntRif]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.EntNombre = new global::Gtk.Entry ();
			this.EntNombre.CanFocus = true;
			this.EntNombre.Name = "EntNombre";
			this.EntNombre.IsEditable = true;
			this.EntNombre.MaxLength = 40;
			this.EntNombre.InvisibleChar = '•';
			this.vbox8.Add (this.EntNombre);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.EntNombre]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.EntDireccion = new global::Gtk.Entry ();
			this.EntDireccion.CanFocus = true;
			this.EntDireccion.Name = "EntDireccion";
			this.EntDireccion.IsEditable = true;
			this.EntDireccion.MaxLength = 60;
			this.EntDireccion.InvisibleChar = '•';
			this.vbox8.Add (this.EntDireccion);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.EntDireccion]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.EntTelefono = new global::Gtk.Entry ();
			this.EntTelefono.CanFocus = true;
			this.EntTelefono.Name = "EntTelefono";
			this.EntTelefono.IsEditable = true;
			this.EntTelefono.MaxLength = 15;
			this.EntTelefono.InvisibleChar = '•';
			this.vbox8.Add (this.EntTelefono);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.EntTelefono]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox5.Add (this.vbox8);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox8]));
			w19.Position = 1;
			this.vbox1.Add (this.hbox5);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Homogeneous = true;
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.BtnEliminar = new global::Gtk.Button ();
			this.BtnEliminar.HeightRequest = 40;
			this.BtnEliminar.Sensitive = false;
			this.BtnEliminar.CanFocus = true;
			this.BtnEliminar.Name = "BtnEliminar";
			this.BtnEliminar.UseUnderline = true;
			this.BtnEliminar.Label = global::Mono.Unix.Catalog.GetString ("Eliminar");
			this.hbox6.Add (this.BtnEliminar);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.BtnEliminar]));
			w21.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox6.Add (this.fixed2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.fixed2]));
			w22.Position = 1;
			// Container child hbox6.Gtk.Box+BoxChild
			this.BtnModificar = new global::Gtk.Button ();
			this.BtnModificar.Sensitive = false;
			this.BtnModificar.CanFocus = true;
			this.BtnModificar.Name = "BtnModificar";
			this.BtnModificar.UseUnderline = true;
			this.BtnModificar.Label = global::Mono.Unix.Catalog.GetString ("Modificar");
			this.hbox6.Add (this.BtnModificar);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.BtnModificar]));
			w23.Position = 2;
			// Container child hbox6.Gtk.Box+BoxChild
			this.BtnIncluir = new global::Gtk.Button ();
			this.BtnIncluir.CanFocus = true;
			this.BtnIncluir.Name = "BtnIncluir";
			this.BtnIncluir.UseUnderline = true;
			this.BtnIncluir.Label = global::Mono.Unix.Catalog.GetString ("Incluir");
			this.hbox6.Add (this.BtnIncluir);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.BtnIncluir]));
			w24.Position = 3;
			this.vbox1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.table2.Add (this.vbox1);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table2 [this.vbox1]));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vbox7.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hseparator3]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.LblFechaHora = new global::Gtk.Label ();
			this.LblFechaHora.Name = "LblFechaHora";
			this.LblFechaHora.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha y Hora");
			this.GtkAlignment1.Add (this.LblFechaHora);
			this.frame4.Add (this.GtkAlignment1);
			this.vbox7.Add (this.frame4);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.frame4]));
			w30.Position = 1;
			w30.Expand = false;
			this.table2.Add (this.vbox7);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table2 [this.vbox7]));
			w31.TopAttach = ((uint)(3));
			w31.BottomAttach = ((uint)(4));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(0));
			this.Add (this.table2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 550;
			this.DefaultHeight = 507;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.EntRif.Changed += new global::System.EventHandler (this.OnEntRifChanged);
			this.EntNombre.Changed += new global::System.EventHandler (this.OnEntNombreChanged);
			this.EntTelefono.Changed += new global::System.EventHandler (this.OnEntTelefonoChanged);
			this.BtnEliminar.Clicked += new global::System.EventHandler (this.OnBtnEliminarClicked);
			this.BtnModificar.Clicked += new global::System.EventHandler (this.OnBtnModificarClicked);
			this.BtnIncluir.Clicked += new global::System.EventHandler (this.OnBtnIncluirClicked);
			this.BtnSalir.Clicked += new global::System.EventHandler (this.OnBtnSalirClicked);
			this.BtnLimpiar.Clicked += new global::System.EventHandler (this.OnBtnLimpiarClicked);
			this.BtnCancelar.Clicked += new global::System.EventHandler (this.OnBtnCancelarClicked);
			this.TvClientes.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTvClientesRowActivated);
		}
	}
}
