
// This file has been generated by the GUI designer. Do not modify.
namespace WhiteRose
{
	public partial class VntLogin
	{
		private global::Gtk.Frame frame3;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.VBox vbox10;
		
		private global::Gtk.Label LblUsuario;
		
		private global::Gtk.Label LblContrasena;
		
		private global::Gtk.VBox vbox11;
		
		private global::Gtk.Entry EntUsuario;
		
		private global::Gtk.Entry EntContrasena;
		
		private global::Gtk.Button BtnAcceder;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.Button BtnOlvideMiContrasena;
		
		private global::Gtk.Button BtnSalir;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Frame frame4;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.Label LblFechaHora;
		
		private global::Gtk.Label LblIngreso;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WhiteRose.VntLogin
			this.Name = "WhiteRose.VntLogin";
			this.Title = global::Mono.Unix.Catalog.GetString ("WhiteRose");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child WhiteRose.VntLogin.Gtk.Container+ContainerChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(1));
			this.frame3.BorderWidth = ((uint)(6));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			this.GtkAlignment.BorderWidth = ((uint)(3));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			this.vbox5.BorderWidth = ((uint)(6));
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Homogeneous = true;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Homogeneous = true;
			// Container child vbox10.Gtk.Box+BoxChild
			this.LblUsuario = new global::Gtk.Label ();
			this.LblUsuario.Name = "LblUsuario";
			this.LblUsuario.Xalign = 1F;
			this.LblUsuario.LabelProp = global::Mono.Unix.Catalog.GetString ("Usuario:");
			this.vbox10.Add (this.LblUsuario);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.LblUsuario]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.LblContrasena = new global::Gtk.Label ();
			this.LblContrasena.Name = "LblContrasena";
			this.LblContrasena.Xalign = 0F;
			this.LblContrasena.LabelProp = global::Mono.Unix.Catalog.GetString ("Contraseña:");
			this.vbox10.Add (this.LblContrasena);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.LblContrasena]));
			w2.Position = 1;
			w2.Expand = false;
			this.hbox4.Add (this.vbox10);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox10]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(7));
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Homogeneous = true;
			this.vbox11.Spacing = 5;
			// Container child vbox11.Gtk.Box+BoxChild
			this.EntUsuario = new global::Gtk.Entry ();
			this.EntUsuario.CanFocus = true;
			this.EntUsuario.Name = "EntUsuario";
			this.EntUsuario.IsEditable = true;
			this.EntUsuario.MaxLength = 10;
			this.EntUsuario.InvisibleChar = '•';
			this.vbox11.Add (this.EntUsuario);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.EntUsuario]));
			w4.Position = 0;
			w4.Expand = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.EntContrasena = new global::Gtk.Entry ();
			this.EntContrasena.CanFocus = true;
			this.EntContrasena.Name = "EntContrasena";
			this.EntContrasena.IsEditable = true;
			this.EntContrasena.MaxLength = 15;
			this.EntContrasena.Visibility = false;
			this.EntContrasena.InvisibleChar = '•';
			this.vbox11.Add (this.EntContrasena);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.EntContrasena]));
			w5.Position = 1;
			w5.Expand = false;
			this.hbox4.Add (this.vbox11);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox11]));
			w6.Position = 1;
			this.vbox5.Add (this.hbox4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox4]));
			w7.Position = 0;
			// Container child vbox5.Gtk.Box+BoxChild
			this.BtnAcceder = new global::Gtk.Button ();
			this.BtnAcceder.HeightRequest = 80;
			this.BtnAcceder.CanFocus = true;
			this.BtnAcceder.Name = "BtnAcceder";
			this.BtnAcceder.UseUnderline = true;
			this.BtnAcceder.BorderWidth = ((uint)(9));
			this.BtnAcceder.Label = global::Mono.Unix.Catalog.GetString ("Ingresar");
			this.vbox5.Add (this.BtnAcceder);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.BtnAcceder]));
			w8.Position = 1;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Homogeneous = true;
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.BtnOlvideMiContrasena = new global::Gtk.Button ();
			this.BtnOlvideMiContrasena.CanFocus = true;
			this.BtnOlvideMiContrasena.Name = "BtnOlvideMiContrasena";
			this.BtnOlvideMiContrasena.UseUnderline = true;
			this.BtnOlvideMiContrasena.BorderWidth = ((uint)(6));
			this.BtnOlvideMiContrasena.Label = global::Mono.Unix.Catalog.GetString ("¡Olvidé mi contraseña!");
			this.hbox10.Add (this.BtnOlvideMiContrasena);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.BtnOlvideMiContrasena]));
			w9.Position = 0;
			// Container child hbox10.Gtk.Box+BoxChild
			this.BtnSalir = new global::Gtk.Button ();
			this.BtnSalir.CanFocus = true;
			this.BtnSalir.Name = "BtnSalir";
			this.BtnSalir.UseUnderline = true;
			this.BtnSalir.BorderWidth = ((uint)(6));
			this.BtnSalir.Label = global::Mono.Unix.Catalog.GetString ("Salir");
			this.hbox10.Add (this.BtnSalir);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.BtnSalir]));
			w10.Position = 1;
			this.vbox5.Add (this.hbox10);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox10]));
			w11.Position = 2;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox5.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hseparator1]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.LblFechaHora = new global::Gtk.Label ();
			this.LblFechaHora.Name = "LblFechaHora";
			this.LblFechaHora.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha y Hora");
			this.GtkAlignment1.Add (this.LblFechaHora);
			this.frame4.Add (this.GtkAlignment1);
			this.vbox5.Add (this.frame4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame4]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			this.GtkAlignment.Add (this.vbox5);
			this.frame3.Add (this.GtkAlignment);
			this.LblIngreso = new global::Gtk.Label ();
			this.LblIngreso.Name = "LblIngreso";
			this.LblIngreso.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Ingresar al Sistema</b>");
			this.LblIngreso.UseMarkup = true;
			this.frame3.LabelWidget = this.LblIngreso;
			this.Add (this.frame3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 398;
			this.DefaultHeight = 273;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.EntUsuario.Changed += new global::System.EventHandler (this.OnEntUsuarioChanged);
			this.BtnAcceder.Clicked += new global::System.EventHandler (this.OnBtnAccederClicked);
			this.BtnOlvideMiContrasena.Clicked += new global::System.EventHandler (this.OnBtnOlvideMiContrasenaClicked);
			this.BtnSalir.Clicked += new global::System.EventHandler (this.OnBtnSalirClicked);
		}
	}
}
