
// This file has been generated by the GUI designer. Do not modify.
namespace WhiteRose
{
	public partial class VntActualizarServicios
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Label LblCodigoServ;
		
		private global::Gtk.Label LblCodDpto;
		
		private global::Gtk.Label LblDescripcion;
		
		private global::Gtk.Label LblCosto;
		
		private global::Gtk.Label LblPrecioDetal;
		
		private global::Gtk.Label LblPrecioMayor;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Entry EntCodigo;
		
		private global::Gtk.ComboBox CbDepartamento;
		
		private global::Gtk.Entry EntDescripcion;
		
		private global::Gtk.Entry EntCosto;
		
		private global::Gtk.Entry EntPrecioD;
		
		private global::Gtk.Entry EntPrecioM;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Button BtnEliminar;
		
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Button BtnModificar;
		
		private global::Gtk.Button BtnIncluir;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView TvServicios;
		
		private global::Gtk.Label LblServiciosActuales;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button BtnLimpiar;
		
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Button BtnCancelar;
		
		private global::Gtk.Button BtnSalir;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.Label LblFechaHora;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WhiteRose.VntActualizarServicios
			this.Name = "WhiteRose.VntActualizarServicios";
			this.Title = global::Mono.Unix.Catalog.GetString ("Actualizar Servicios");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child WhiteRose.VntActualizarServicios.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(6));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			this.hbox3.BorderWidth = ((uint)(3));
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Homogeneous = true;
			this.vbox3.Spacing = 15;
			// Container child vbox3.Gtk.Box+BoxChild
			this.LblCodigoServ = new global::Gtk.Label ();
			this.LblCodigoServ.Name = "LblCodigoServ";
			this.LblCodigoServ.Xalign = 1F;
			this.LblCodigoServ.LabelProp = global::Mono.Unix.Catalog.GetString ("Código:");
			this.vbox3.Add (this.LblCodigoServ);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.LblCodigoServ]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.LblCodDpto = new global::Gtk.Label ();
			this.LblCodDpto.Name = "LblCodDpto";
			this.LblCodDpto.Xalign = 1F;
			this.LblCodDpto.LabelProp = global::Mono.Unix.Catalog.GetString ("Departamento:");
			this.vbox3.Add (this.LblCodDpto);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.LblCodDpto]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.LblDescripcion = new global::Gtk.Label ();
			this.LblDescripcion.Name = "LblDescripcion";
			this.LblDescripcion.Xalign = 1F;
			this.LblDescripcion.LabelProp = global::Mono.Unix.Catalog.GetString ("Descripción:");
			this.vbox3.Add (this.LblDescripcion);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.LblDescripcion]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.LblCosto = new global::Gtk.Label ();
			this.LblCosto.Name = "LblCosto";
			this.LblCosto.Xalign = 1F;
			this.LblCosto.LabelProp = global::Mono.Unix.Catalog.GetString ("Costo:");
			this.vbox3.Add (this.LblCosto);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.LblCosto]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.LblPrecioDetal = new global::Gtk.Label ();
			this.LblPrecioDetal.Name = "LblPrecioDetal";
			this.LblPrecioDetal.Xalign = 1F;
			this.LblPrecioDetal.LabelProp = global::Mono.Unix.Catalog.GetString ("Precio (Detal):");
			this.vbox3.Add (this.LblPrecioDetal);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.LblPrecioDetal]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.LblPrecioMayor = new global::Gtk.Label ();
			this.LblPrecioMayor.Name = "LblPrecioMayor";
			this.LblPrecioMayor.Xalign = 1F;
			this.LblPrecioMayor.LabelProp = global::Mono.Unix.Catalog.GetString ("Precio (Mayor):");
			this.vbox3.Add (this.LblPrecioMayor);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.LblPrecioMayor]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			this.hbox3.Add (this.vbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox3]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Homogeneous = true;
			this.vbox4.Spacing = 15;
			// Container child vbox4.Gtk.Box+BoxChild
			this.EntCodigo = new global::Gtk.Entry ();
			this.EntCodigo.CanFocus = true;
			this.EntCodigo.Name = "EntCodigo";
			this.EntCodigo.IsEditable = true;
			this.EntCodigo.MaxLength = 4;
			this.EntCodigo.InvisibleChar = '•';
			this.vbox4.Add (this.EntCodigo);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.EntCodigo]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.CbDepartamento = global::Gtk.ComboBox.NewText ();
			this.CbDepartamento.Name = "CbDepartamento";
			this.vbox4.Add (this.CbDepartamento);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.CbDepartamento]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.EntDescripcion = new global::Gtk.Entry ();
			this.EntDescripcion.CanFocus = true;
			this.EntDescripcion.Name = "EntDescripcion";
			this.EntDescripcion.IsEditable = true;
			this.EntDescripcion.MaxLength = 40;
			this.EntDescripcion.InvisibleChar = '•';
			this.vbox4.Add (this.EntDescripcion);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.EntDescripcion]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.EntCosto = new global::Gtk.Entry ();
			this.EntCosto.CanFocus = true;
			this.EntCosto.Name = "EntCosto";
			this.EntCosto.IsEditable = true;
			this.EntCosto.MaxLength = 15;
			this.EntCosto.InvisibleChar = '•';
			this.vbox4.Add (this.EntCosto);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.EntCosto]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.EntPrecioD = new global::Gtk.Entry ();
			this.EntPrecioD.CanFocus = true;
			this.EntPrecioD.Name = "EntPrecioD";
			this.EntPrecioD.IsEditable = true;
			this.EntPrecioD.MaxLength = 15;
			this.EntPrecioD.InvisibleChar = '•';
			this.vbox4.Add (this.EntPrecioD);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.EntPrecioD]));
			w12.Position = 4;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.EntPrecioM = new global::Gtk.Entry ();
			this.EntPrecioM.CanFocus = true;
			this.EntPrecioM.Name = "EntPrecioM";
			this.EntPrecioM.IsEditable = true;
			this.EntPrecioM.MaxLength = 15;
			this.EntPrecioM.InvisibleChar = '•';
			this.vbox4.Add (this.EntPrecioM);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.EntPrecioM]));
			w13.Position = 5;
			w13.Expand = false;
			w13.Fill = false;
			this.hbox3.Add (this.vbox4);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox4]));
			w14.Position = 1;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w15.Position = 0;
			w15.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.BtnEliminar = new global::Gtk.Button ();
			this.BtnEliminar.Sensitive = false;
			this.BtnEliminar.CanFocus = true;
			this.BtnEliminar.Name = "BtnEliminar";
			this.BtnEliminar.UseUnderline = true;
			this.BtnEliminar.Label = global::Mono.Unix.Catalog.GetString ("Eliminar");
			this.hbox2.Add (this.BtnEliminar);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.BtnEliminar]));
			w16.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox2.Add (this.fixed2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed2]));
			w17.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.BtnModificar = new global::Gtk.Button ();
			this.BtnModificar.HeightRequest = 40;
			this.BtnModificar.Sensitive = false;
			this.BtnModificar.CanFocus = true;
			this.BtnModificar.Name = "BtnModificar";
			this.BtnModificar.UseUnderline = true;
			this.BtnModificar.Label = global::Mono.Unix.Catalog.GetString ("Modificar");
			this.hbox2.Add (this.BtnModificar);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.BtnModificar]));
			w18.Position = 2;
			// Container child hbox2.Gtk.Box+BoxChild
			this.BtnIncluir = new global::Gtk.Button ();
			this.BtnIncluir.HeightRequest = 30;
			this.BtnIncluir.Sensitive = false;
			this.BtnIncluir.CanFocus = true;
			this.BtnIncluir.Name = "BtnIncluir";
			this.BtnIncluir.UseUnderline = true;
			this.BtnIncluir.Label = global::Mono.Unix.Catalog.GetString ("Incluir");
			this.hbox2.Add (this.BtnIncluir);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.BtnIncluir]));
			w19.Position = 3;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			this.GtkAlignment1.BorderWidth = ((uint)(6));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TvServicios = new global::Gtk.TreeView ();
			this.TvServicios.CanFocus = true;
			this.TvServicios.Name = "TvServicios";
			this.GtkScrolledWindow.Add (this.TvServicios);
			this.GtkAlignment1.Add (this.GtkScrolledWindow);
			this.frame2.Add (this.GtkAlignment1);
			this.LblServiciosActuales = new global::Gtk.Label ();
			this.LblServiciosActuales.Name = "LblServiciosActuales";
			this.LblServiciosActuales.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Servicios Actuales</b>");
			this.LblServiciosActuales.UseMarkup = true;
			this.frame2.LabelWidget = this.LblServiciosActuales;
			this.vbox1.Add (this.frame2);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame2]));
			w24.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BtnLimpiar = new global::Gtk.Button ();
			this.BtnLimpiar.Sensitive = false;
			this.BtnLimpiar.CanFocus = true;
			this.BtnLimpiar.Name = "BtnLimpiar";
			this.BtnLimpiar.UseUnderline = true;
			this.BtnLimpiar.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
			this.hbox1.Add (this.BtnLimpiar);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.BtnLimpiar]));
			w25.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixed1]));
			w26.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BtnCancelar = new global::Gtk.Button ();
			this.BtnCancelar.CanFocus = true;
			this.BtnCancelar.Name = "BtnCancelar";
			this.BtnCancelar.UseUnderline = true;
			this.BtnCancelar.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox1.Add (this.BtnCancelar);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.BtnCancelar]));
			w27.Position = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BtnSalir = new global::Gtk.Button ();
			this.BtnSalir.HeightRequest = 30;
			this.BtnSalir.CanFocus = true;
			this.BtnSalir.Name = "BtnSalir";
			this.BtnSalir.UseUnderline = true;
			this.BtnSalir.Label = global::Mono.Unix.Catalog.GetString ("Salir");
			this.hbox1.Add (this.BtnSalir);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.BtnSalir]));
			w28.Position = 3;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w29.Position = 3;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w30.Position = 4;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.LblFechaHora = new global::Gtk.Label ();
			this.LblFechaHora.Name = "LblFechaHora";
			this.LblFechaHora.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha y Hora");
			this.GtkAlignment.Add (this.LblFechaHora);
			this.frame1.Add (this.GtkAlignment);
			this.vbox1.Add (this.frame1);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
			w33.Position = 5;
			w33.Expand = false;
			w33.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 411;
			this.DefaultHeight = 650;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.EntCodigo.Changed += new global::System.EventHandler (this.OnEntCodigoChanged);
			this.EntCosto.Changed += new global::System.EventHandler (this.OnEntCostoChanged);
			this.EntPrecioD.Changed += new global::System.EventHandler (this.OnEntPrecioDChanged);
			this.EntPrecioM.Changed += new global::System.EventHandler (this.OnEntPrecioMChanged);
			this.BtnEliminar.Clicked += new global::System.EventHandler (this.OnBtnEliminarClicked);
			this.BtnModificar.Clicked += new global::System.EventHandler (this.OnBtnModificarClicked);
			this.BtnIncluir.Clicked += new global::System.EventHandler (this.OnBtnIncluirClicked);
			this.TvServicios.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTvServiciosRowActivated);
			this.BtnLimpiar.Clicked += new global::System.EventHandler (this.OnBtnLimpiarClicked);
			this.BtnCancelar.Clicked += new global::System.EventHandler (this.OnBtnCancelarClicked);
			this.BtnSalir.Clicked += new global::System.EventHandler (this.OnBtnSalirClicked);
		}
	}
}
