
// This file has been generated by the GUI designer. Do not modify.
namespace WhiteRose
{
	public partial class VntSplashScreen
	{
		private global::Gtk.Image ImgSplashScreen;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WhiteRose.VntSplashScreen
			this.Name = "WhiteRose.VntSplashScreen";
			this.Title = global::Mono.Unix.Catalog.GetString ("VntSplashScreen");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child WhiteRose.VntSplashScreen.Gtk.Container+ContainerChild
			this.ImgSplashScreen = new global::Gtk.Image ();
			this.ImgSplashScreen.Name = "ImgSplashScreen";
			this.Add (this.ImgSplashScreen);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 52;
			this.DefaultHeight = 62;
			this.Show ();
		}
	}
}
