
// This file has been generated by the GUI designer. Do not modify.
namespace WhiteRose
{
	public partial class VntReportesVentas
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Frame frame7;
		
		private global::Gtk.Alignment GtkAlignment6;
		
		private global::Gtk.Notebook notebook2;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.Frame frame5;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Label LblFechaI;
		
		private global::Gtk.Entry EntFechaI;
		
		private global::Gtk.Button BtnVerCalendarioFechaI;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Label LblFechaF;
		
		private global::Gtk.Entry EntFechaF;
		
		private global::Gtk.Button BtnVerCalendarioFechaF;
		
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Button BtnBuscarFact;
		
		private global::Gtk.Label LblFechaC;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView TvFacturas;
		
		private global::Gtk.Label LblReportesVentas1;
		
		private global::Gtk.Label LblReportesVentas;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.Frame frame4;
		
		private global::Gtk.Alignment GtkAlignment3;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.Label LblServicios;
		
		private global::Gtk.Entry EntCodServ;
		
		private global::Gtk.Button BtnBuscarServ;
		
		private global::Gtk.Label LblDatosS;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView TvDetalles;
		
		private global::Gtk.Label LblReportesServicios2;
		
		private global::Gtk.Label LblReportesServicios1;
		
		private global::Gtk.Label LblEstadisticas1;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Button BtnLimpiar;
		
		private global::Gtk.Button BtnCancelar;
		
		private global::Gtk.Button BtnSalir;
		
		private global::Gtk.Frame frame3;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.Label LblFechaHora;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WhiteRose.VntReportesVentas
			this.Name = "WhiteRose.VntReportesVentas";
			this.Title = global::Mono.Unix.Catalog.GetString ("Reportes de Ventas");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-index", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child WhiteRose.VntReportesVentas.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(6));
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame7 = new global::Gtk.Frame ();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment6 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment6.Name = "GtkAlignment6";
			this.GtkAlignment6.LeftPadding = ((uint)(12));
			this.GtkAlignment6.BorderWidth = ((uint)(9));
			// Container child GtkAlignment6.Gtk.Container+ContainerChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 1;
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(1));
			this.frame5.BorderWidth = ((uint)(9));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			this.GtkAlignment4.BorderWidth = ((uint)(6));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.LblFechaI = new global::Gtk.Label ();
			this.LblFechaI.Name = "LblFechaI";
			this.LblFechaI.Xalign = 1F;
			this.LblFechaI.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha de Inicio:");
			this.hbox9.Add (this.LblFechaI);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.LblFechaI]));
			w1.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.EntFechaI = new global::Gtk.Entry ();
			this.EntFechaI.CanFocus = true;
			this.EntFechaI.Name = "EntFechaI";
			this.EntFechaI.IsEditable = true;
			this.EntFechaI.MaxLength = 10;
			this.EntFechaI.InvisibleChar = '•';
			this.hbox9.Add (this.EntFechaI);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.EntFechaI]));
			w2.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.BtnVerCalendarioFechaI = new global::Gtk.Button ();
			this.BtnVerCalendarioFechaI.CanFocus = true;
			this.BtnVerCalendarioFechaI.Name = "BtnVerCalendarioFechaI";
			this.BtnVerCalendarioFechaI.UseUnderline = true;
			this.BtnVerCalendarioFechaI.Label = global::Mono.Unix.Catalog.GetString ("...");
			this.hbox9.Add (this.BtnVerCalendarioFechaI);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.BtnVerCalendarioFechaI]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.hbox7.Add (this.hbox9);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hbox9]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.LblFechaF = new global::Gtk.Label ();
			this.LblFechaF.Name = "LblFechaF";
			this.LblFechaF.Xalign = 1F;
			this.LblFechaF.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha Final:");
			this.hbox8.Add (this.LblFechaF);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.LblFechaF]));
			w5.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.EntFechaF = new global::Gtk.Entry ();
			this.EntFechaF.CanFocus = true;
			this.EntFechaF.Name = "EntFechaF";
			this.EntFechaF.IsEditable = true;
			this.EntFechaF.MaxLength = 10;
			this.EntFechaF.InvisibleChar = '•';
			this.hbox8.Add (this.EntFechaF);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.EntFechaF]));
			w6.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.BtnVerCalendarioFechaF = new global::Gtk.Button ();
			this.BtnVerCalendarioFechaF.CanFocus = true;
			this.BtnVerCalendarioFechaF.Name = "BtnVerCalendarioFechaF";
			this.BtnVerCalendarioFechaF.UseUnderline = true;
			this.BtnVerCalendarioFechaF.Label = global::Mono.Unix.Catalog.GetString ("...");
			this.hbox8.Add (this.BtnVerCalendarioFechaF);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.BtnVerCalendarioFechaF]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.WidthRequest = 39;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox8.Add (this.fixed1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.fixed1]));
			w8.Position = 3;
			this.hbox7.Add (this.hbox8);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hbox8]));
			w9.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.BtnBuscarFact = new global::Gtk.Button ();
			this.BtnBuscarFact.HeightRequest = 30;
			this.BtnBuscarFact.CanFocus = true;
			this.BtnBuscarFact.Name = "BtnBuscarFact";
			this.BtnBuscarFact.UseUnderline = true;
			this.BtnBuscarFact.Label = global::Mono.Unix.Catalog.GetString ("Buscar");
			this.hbox7.Add (this.BtnBuscarFact);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.BtnBuscarFact]));
			w10.Position = 2;
			this.GtkAlignment4.Add (this.hbox7);
			this.frame5.Add (this.GtkAlignment4);
			this.LblFechaC = new global::Gtk.Label ();
			this.LblFechaC.Name = "LblFechaC";
			this.LblFechaC.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Fechas de Consulta</b>");
			this.LblFechaC.UseMarkup = true;
			this.frame5.LabelWidget = this.LblFechaC;
			this.vbox6.Add (this.frame5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.frame5]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
			this.frame1.BorderWidth = ((uint)(9));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			this.GtkAlignment.BorderWidth = ((uint)(6));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TvFacturas = new global::Gtk.TreeView ();
			this.TvFacturas.CanFocus = true;
			this.TvFacturas.Name = "TvFacturas";
			this.GtkScrolledWindow.Add (this.TvFacturas);
			this.GtkAlignment.Add (this.GtkScrolledWindow);
			this.frame1.Add (this.GtkAlignment);
			this.LblReportesVentas1 = new global::Gtk.Label ();
			this.LblReportesVentas1.Name = "LblReportesVentas1";
			this.LblReportesVentas1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Reporte</b>");
			this.LblReportesVentas1.UseMarkup = true;
			this.frame1.LabelWidget = this.LblReportesVentas1;
			this.vbox6.Add (this.frame1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.frame1]));
			w17.Position = 1;
			this.notebook2.Add (this.vbox6);
			// Notebook tab
			this.LblReportesVentas = new global::Gtk.Label ();
			this.LblReportesVentas.Name = "LblReportesVentas";
			this.LblReportesVentas.LabelProp = global::Mono.Unix.Catalog.GetString ("Reporte de Ventas");
			this.notebook2.SetTabLabel (this.vbox6, this.LblReportesVentas);
			this.LblReportesVentas.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(1));
			this.frame4.BorderWidth = ((uint)(9));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			this.GtkAlignment3.BorderWidth = ((uint)(6));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.LblServicios = new global::Gtk.Label ();
			this.LblServicios.Name = "LblServicios";
			this.LblServicios.LabelProp = global::Mono.Unix.Catalog.GetString ("Código del Servicio: ");
			this.hbox10.Add (this.LblServicios);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.LblServicios]));
			w19.Position = 0;
			// Container child hbox10.Gtk.Box+BoxChild
			this.EntCodServ = new global::Gtk.Entry ();
			this.EntCodServ.CanFocus = true;
			this.EntCodServ.Name = "EntCodServ";
			this.EntCodServ.IsEditable = true;
			this.EntCodServ.MaxLength = 3;
			this.EntCodServ.InvisibleChar = '•';
			this.hbox10.Add (this.EntCodServ);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.EntCodServ]));
			w20.Position = 1;
			// Container child hbox10.Gtk.Box+BoxChild
			this.BtnBuscarServ = new global::Gtk.Button ();
			this.BtnBuscarServ.HeightRequest = 40;
			this.BtnBuscarServ.CanFocus = true;
			this.BtnBuscarServ.Name = "BtnBuscarServ";
			this.BtnBuscarServ.UseUnderline = true;
			this.BtnBuscarServ.Label = global::Mono.Unix.Catalog.GetString ("Buscar");
			this.hbox10.Add (this.BtnBuscarServ);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.BtnBuscarServ]));
			w21.Position = 2;
			this.GtkAlignment3.Add (this.hbox10);
			this.frame4.Add (this.GtkAlignment3);
			this.LblDatosS = new global::Gtk.Label ();
			this.LblDatosS.Name = "LblDatosS";
			this.LblDatosS.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Datos del Servicio</b>");
			this.LblDatosS.UseMarkup = true;
			this.frame4.LabelWidget = this.LblDatosS;
			this.vbox7.Add (this.frame4);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.frame4]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(1));
			this.frame2.BorderWidth = ((uint)(9));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			this.GtkAlignment1.BorderWidth = ((uint)(6));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.TvDetalles = new global::Gtk.TreeView ();
			this.TvDetalles.CanFocus = true;
			this.TvDetalles.Name = "TvDetalles";
			this.GtkScrolledWindow1.Add (this.TvDetalles);
			this.GtkAlignment1.Add (this.GtkScrolledWindow1);
			this.frame2.Add (this.GtkAlignment1);
			this.LblReportesServicios2 = new global::Gtk.Label ();
			this.LblReportesServicios2.Name = "LblReportesServicios2";
			this.LblReportesServicios2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Reporte</b>");
			this.LblReportesServicios2.UseMarkup = true;
			this.frame2.LabelWidget = this.LblReportesServicios2;
			this.vbox7.Add (this.frame2);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.frame2]));
			w28.Position = 1;
			this.notebook2.Add (this.vbox7);
			global::Gtk.Notebook.NotebookChild w29 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.vbox7]));
			w29.Position = 1;
			// Notebook tab
			this.LblReportesServicios1 = new global::Gtk.Label ();
			this.LblReportesServicios1.Name = "LblReportesServicios1";
			this.LblReportesServicios1.LabelProp = global::Mono.Unix.Catalog.GetString ("Reporte de Servicios");
			this.notebook2.SetTabLabel (this.vbox7, this.LblReportesServicios1);
			this.LblReportesServicios1.ShowAll ();
			this.GtkAlignment6.Add (this.notebook2);
			this.frame7.Add (this.GtkAlignment6);
			this.LblEstadisticas1 = new global::Gtk.Label ();
			this.LblEstadisticas1.Name = "LblEstadisticas1";
			this.LblEstadisticas1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Mr. Robot - Estadísticas de Ventas</b>");
			this.LblEstadisticas1.UseMarkup = true;
			this.frame7.LabelWidget = this.LblEstadisticas1;
			this.vbox2.Add (this.frame7);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame7]));
			w32.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			this.hbox2.BorderWidth = ((uint)(6));
			// Container child hbox2.Gtk.Box+BoxChild
			this.BtnLimpiar = new global::Gtk.Button ();
			this.BtnLimpiar.CanFocus = true;
			this.BtnLimpiar.Name = "BtnLimpiar";
			this.BtnLimpiar.UseUnderline = true;
			this.BtnLimpiar.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
			this.hbox2.Add (this.BtnLimpiar);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.BtnLimpiar]));
			w33.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.BtnCancelar = new global::Gtk.Button ();
			this.BtnCancelar.CanFocus = true;
			this.BtnCancelar.Name = "BtnCancelar";
			this.BtnCancelar.UseUnderline = true;
			this.BtnCancelar.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox2.Add (this.BtnCancelar);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.BtnCancelar]));
			w34.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.BtnSalir = new global::Gtk.Button ();
			this.BtnSalir.HeightRequest = 40;
			this.BtnSalir.CanFocus = true;
			this.BtnSalir.Name = "BtnSalir";
			this.BtnSalir.UseUnderline = true;
			this.BtnSalir.Label = global::Mono.Unix.Catalog.GetString ("Salir");
			this.hbox2.Add (this.BtnSalir);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.BtnSalir]));
			w35.Position = 2;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(1));
			this.frame3.BorderWidth = ((uint)(6));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.LblFechaHora = new global::Gtk.Label ();
			this.LblFechaHora.Name = "LblFechaHora";
			this.LblFechaHora.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha y Hora");
			this.LblFechaHora.Justify = ((global::Gtk.Justification)(2));
			this.GtkAlignment2.Add (this.LblFechaHora);
			this.frame3.Add (this.GtkAlignment2);
			this.vbox2.Add (this.frame3);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame3]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 892;
			this.DefaultHeight = 593;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.BtnVerCalendarioFechaI.Clicked += new global::System.EventHandler (this.OnBtnVerCalendarioFechaIClicked);
			this.BtnVerCalendarioFechaF.Clicked += new global::System.EventHandler (this.OnBtnVerCalendarioFechaFClicked);
			this.BtnBuscarFact.Clicked += new global::System.EventHandler (this.OnBtnBuscarFactClicked);
			this.TvFacturas.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTvFacturasRowActivated);
			this.EntCodServ.Changed += new global::System.EventHandler (this.OnEntCodServChanged);
			this.BtnBuscarServ.Clicked += new global::System.EventHandler (this.OnBtnBuscarServClicked);
			this.BtnLimpiar.Clicked += new global::System.EventHandler (this.OnBtnLimpiarClicked);
			this.BtnCancelar.Clicked += new global::System.EventHandler (this.OnBtnCancelarClicked);
			this.BtnSalir.Clicked += new global::System.EventHandler (this.OnBtnSalirClicked);
		}
	}
}
